/*
 * JOsIFrm.java
 *
 * Created on 11 25, 10, 10:25:07 AM
 */

package gov.cont;

/**
 *
 * @author felix
 */
public class ContractIFrame extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = -2550722043199031989L;

    private final java.util.ArrayList<String> arOffice = new java.util.ArrayList<>();
    
    /** Creates new form JOsIFrm */
    @SuppressWarnings("this-escape")
    public ContractIFrame() {initComponents();}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUniqueID = new javax.swing.JTextField();
        btnOpen = new javax.swing.JButton();
        tabPane = new javax.swing.JTabbedPane();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        txtSurName = new javax.swing.JTextField();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        txtGiveName = new javax.swing.JTextField();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        txtMidInit = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel15 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        fmtRate = new javax.swing.JFormattedTextField();
        btnLookUp = new javax.swing.JButton();
        txtRanking = new javax.swing.JTextField();
        btnLookPos = new javax.swing.JButton();
        txtEmpID = new javax.swing.JTextField();
        javax.swing.JLabel jLabel14 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel16 = new javax.swing.JLabel();
        dtpBirthday = new com.toedter.calendar.JDateChooser();
        cboSuffix = new javax.swing.JComboBox<>();
        cboOffice = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel18 = new javax.swing.JLabel();
        fmtAccount = new javax.swing.JFormattedTextField();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel19 = new javax.swing.JLabel();
        cboGender = new javax.swing.JComboBox<>();
        btnSetNull = new javax.swing.JButton();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        tblHuman = new javax.swing.JTable();
        javax.swing.JLabel jLabel17 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        javax.swing.JMenuBar MenuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu FileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem SavePopup = new javax.swing.JMenuItem();
        ErasePopup = new javax.swing.JMenuItem();
        javax.swing.JMenu FormMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem ClearPopup = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator1 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenuItem ClosePopup = new javax.swing.JMenuItem();

        txtUniqueID.setEditable(false);

        btnOpen.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/open.png"))); // NOI18N
        btnOpen.setText("jButton1");
        btnOpen.setBorder(null);
        btnOpen.setBorderPainted(false);
        btnOpen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });

        setClosable(true);
        setTitle("Contractual Information");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/leaf.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tabPane.setFocusable(false);
        tabPane.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jPanel1.setFocusable(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(414, 220));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setText("Last Name");

        txtSurName.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setText("Suffix");

        txtGiveName.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setText("First Name");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel12.setText("Middle Name");

        txtMidInit.setEditable(false);

        txtAddress.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setText("Address");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel15.setText("Position");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Salary");

        fmtRate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        fmtRate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fmtRate.setValue(0D);

        btnLookUp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnLookUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/plus.png"))); // NOI18N
        btnLookUp.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLookUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookUpActionPerformed(evt);
            }
        });

        txtRanking.setEditable(false);

        btnLookPos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnLookPos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/plus.png"))); // NOI18N
        btnLookPos.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnLookPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookposActionPerformed(evt);
            }
        });

        txtEmpID.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel14.setText("I.D. #");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel16.setText("Birthday");

        dtpBirthday.setDateFormatString("MM/dd/yyyy");
        dtpBirthday.setEnabled(false);

        cboSuffix.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cboSuffix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "JR", "JR II", "SR", "I", "II", "III", "IV", "V", "VI" }));

        cboOffice.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel18.setText("Office");

        try {
            fmtAccount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#-#####-###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Bank Acct");

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel19.setText("Gender");

        cboGender.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Male", "Female" }));

        btnSetNull.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnSetNull.setText("clear");
        btnSetNull.setBorderPainted(false);
        btnSetNull.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSetNull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setNullActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel5)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddress)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtRanking)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLookPos))
                            .addComponent(cboOffice, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMidInit, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dtpBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(fmtRate, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fmtAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSetNull)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtSurName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLookUp))
                                    .addComponent(txtGiveName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel14)))
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtEmpID)
                            .addComponent(cboSuffix, 0, 104, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLookUp)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtSurName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(cboSuffix, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiveName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtMidInit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(dtpBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(cboGender, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLookPos)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fmtRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fmtAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnSetNull))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPane.addTab("Information", jPanel1);

        jPanel2.setFocusable(false);

        tblHuman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Last Name", "First Name", "Middle", "idkey", "<-"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHuman);
        if (tblHuman.getColumnModel().getColumnCount() > 0) {
            tblHuman.getColumnModel().getColumn(0).setPreferredWidth(160);
            tblHuman.getColumnModel().getColumn(1).setPreferredWidth(160);
            tblHuman.getColumnModel().getColumn(3).setMinWidth(0);
            tblHuman.getColumnModel().getColumn(3).setPreferredWidth(0);
            tblHuman.getColumnModel().getColumn(3).setMaxWidth(0);
            tblHuman.getColumnModel().getColumn(4).setPreferredWidth(10);
            tblHuman.getColumnModel().getColumn(4).setCellEditor(new tables.ButtonEditor(btnOpen));
            tblHuman.getColumnModel().getColumn(4).setCellRenderer(new tables.ButtonRenderer(getClass().getResource("/gov/imajen/open.png")));
        }

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel17.setText("Name");

        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/search.png"))); // NOI18N
        btnFind.setBorderPainted(false);
        btnFind.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindfindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFind)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );

        getRootPane().setDefaultButton(btnFind);

        tabPane.addTab("Search", jPanel2);

        FileMenu.setText("RECORD");
        FileMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        FileMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                FileMenuMenuSelected(evt);
            }
        });

        SavePopup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        SavePopup.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        SavePopup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/save.png"))); // NOI18N
        SavePopup.setText("SAVE/UPDATE");
        SavePopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavePopupActionPerformed(evt);
            }
        });
        FileMenu.add(SavePopup);

        ErasePopup.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ErasePopup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/delete.png"))); // NOI18N
        ErasePopup.setText("ERASE");
        ErasePopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErasePopupActionPerformed(evt);
            }
        });
        FileMenu.add(ErasePopup);

        MenuBar.add(FileMenu);

        FormMenu.setText("FORM");
        FormMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        ClearPopup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ClearPopup.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ClearPopup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/filenew.png"))); // NOI18N
        ClearPopup.setText("CLEAR");
        ClearPopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearPopupActionPerformed(evt);
            }
        });
        FormMenu.add(ClearPopup);
        FormMenu.add(jSeparator1);

        ClosePopup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ClosePopup.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ClosePopup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/close.png"))); // NOI18N
        ClosePopup.setText("CLOSE");
        ClosePopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosePopupActionPerformed(evt);
            }
        });
        FormMenu.add(ClosePopup);

        MenuBar.add(FormMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ClearPopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearPopupActionPerformed
        // TODO add your handling code here:
        txtUniqueID.setText("");
        txtEmpID   .setText("");
        txtSurName .setText("");
        txtGiveName.setText("");
        txtMidInit .setText("");
        txtAddress .setText("");
        fmtRate    .setValue(0D);
        fmtAccount.setValue(null);
    }//GEN-LAST:event_ClearPopupActionPerformed

    private void ClosePopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosePopupActionPerformed
        // TODO add your handling code here:
        doDefaultCloseAction();
    }//GEN-LAST:event_ClosePopupActionPerformed

    private void SavePopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavePopupActionPerformed
        // TODO add your handling code here:
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink()) {
            fmtRate.commitEdit(); 
            if (!fmtAccount.getText().equals(" -     -   - ")) fmtAccount.commitEdit();

            int index = cboOffice.getSelectedIndex();

            jdbc.setAutoCommit(false);
            try (java.sql.Statement stmt = jdbc.createStatement()) {
                String ranking = txtRanking.getText(),
                       birthday = new java.text.SimpleDateFormat("yyyy-MM-dd").format(dtpBirthday.getDate()),
                       Suffix   = cboSuffix.getSelectedItem().toString(),
                       Office   = arOffice.get(index);
                Short gender = (short)cboGender.getSelectedIndex();

                dbase.SQLExecute saver = new dbase.SQLExecute("psnl.jobworker");
                saver.FieldName("uniqkey",   !NUMERIC, enums.Take.InsertOnly, CONDITION, txtUniqueID.getText());
                saver.FieldName("empid",     !NUMERIC, enums.Take.InsertUpdate, txtEmpID.getText());
                saver.FieldName("suffix",    !NUMERIC, enums.Take.InsertUpdate, Suffix);
                saver.FieldName("lastname",  !NUMERIC, enums.Take.InsertUpdate, txtSurName.getText().toUpperCase());
                saver.FieldName("firstname", !NUMERIC, enums.Take.InsertUpdate, txtGiveName.getText().toUpperCase());
                if (!txtMidInit.getText().isEmpty())
                    saver.FieldName("midname",   !NUMERIC, enums.Take.InsertUpdate, txtMidInit.getText().toUpperCase());
                if (!txtAddress.getText().isEmpty())
                    saver.FieldName("address",   !NUMERIC, enums.Take.InsertUpdate, txtAddress.getText());
                saver.FieldName("birthday",  !NUMERIC, enums.Take.InsertUpdate, birthday);
                saver.FieldName("jobdesc",   !NUMERIC, enums.Take.InsertUpdate, ranking);
                saver.FieldName("offcloc",   !NUMERIC, enums.Take.InsertUpdate, Office);
                saver.FieldName("payrate",    NUMERIC, enums.Take.InsertUpdate, fmtRate.getValue());
                if (fmtAccount.getValue() == null)
                    saver.FieldName("bank_acct",  NUMERIC, enums.Take.InsertUpdate, null);
                else
                    saver.FieldName("bank_acct", !NUMERIC, enums.Take.InsertUpdate, fmtAccount.getValue());
                saver.FieldName("inputby",   !NUMERIC, enums.Take.InsertUpdate, System.getProperty("USERID"));
                saver.FieldName("gender",   !NUMERIC, enums.Take.InsertUpdate, gender);
                stmt.executeUpdate("ALTER TABLE psnl.jobworker DISABLE TRIGGER update_account;");
                int success = stmt.executeUpdate(saver.Perform(enums.Fire.doUpdate));
                stmt.executeUpdate("ALTER TABLE psnl.jobworker ENABLE TRIGGER update_account;");

                if (success == 0)
                    stmt.executeUpdate(saver.Perform(enums.Fire.doInsert));
                jdbc.commit();

                javax.swing.JOptionPane.showMessageDialog(this, "Record saved successfully.", title, javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
                
                txtAddress .setText("");
                txtEmpID   .setText("");
                txtGiveName.setText("");
                txtMidInit .setText("");
                txtSearch  .setText("");
                txtSurName .setText("");
                txtUniqueID.setText("");
                fmtRate    .setValue(0D);
                dtpBirthday.setDate(null);
                cboSuffix  .setSelectedItem(null);
                txtRanking .setText("");

                txtSurName .setEditable(false);
                txtGiveName.setEditable(false);
                txtMidInit .setEditable(false);
                dtpBirthday.setEnabled(false);
                txtAddress .setEditable(false);
                fmtAccount .setValue(null);

                btnLookUp  .setEnabled(true);
            


            } catch (java.sql.SQLException exs) {
                jdbc.rollback();
                javax.swing.JOptionPane.showMessageDialog(this, exs.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
                java.util.logging.Logger.getLogger(ContractIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, exs);
            }

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(ContractIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_SavePopupActionPerformed

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        // TODO add your handling code here:
        int selRow = tblHuman.getSelectedRow();
        if (selRow < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "SELECT A ROW TO RETRIEVE", title, javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        selRow = tblHuman.convertRowIndexToModel(selRow);
        
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.Statement stmt = jdbc.createStatement();
                java.sql.ResultSet rst = stmt.executeQuery(
                    "SELECT " +
                        "uniqkey, " +      // 1
                        "empid, " +        // 2
                        "suffix, " +       // 3
                        "lastname, " +     // 4
                        "firstname, " +    // 5
                        "midname, " +      // 6
                        "birthday, " +     // 7
                        "address, " +      // 8
                        "jobdesc, " +      // 9
                        "offcloc, " +      //10
                        "payrate, " +      //11
                        "bank_acct, " +    //12
                        "gender " +        //13
                    "FROM " +
                        "psnl.jobworker " +
                    "WHERE " +
                        "(uniqkey = '" + tblHuman.getValueAt(selRow, 3) + "')")) {
            if (rst.next()) {
                String Office = rst.getString(10);
                txtUniqueID.setText(rst.getString(1));
                txtEmpID   .setText(rst.getString(2));
                cboSuffix  .setSelectedItem(rst.getString(3));
                txtSurName .setText(rst.getString(4));
                txtGiveName.setText(rst.getString(5));
                txtMidInit .setText(rst.getString(6));
                dtpBirthday.setDate(rst.getDate(7));
                txtAddress .setText(rst.getString(8));
                txtRanking .setText(rst.getString(9));
                
                int index = arOffice.indexOf(Office);
                cboOffice.setSelectedIndex(index);
                fmtRate    .setValue(rst.getDouble(11));
                fmtAccount.setValue(rst.getString(12));
                cboGender.setSelectedIndex(rst.getShort(13));
                
                tabPane.setSelectedIndex(0);
                
            } else
                javax.swing.JOptionPane.showMessageDialog(this, "Record not found.", title, javax.swing.JOptionPane.WARNING_MESSAGE);

            txtSurName.setEditable(true);
            txtGiveName.setEditable(true);
            txtMidInit.setEditable(true);
            dtpBirthday.setEnabled(true);
            txtAddress.setEditable(true);
            
            btnLookUp.setEnabled(false);



        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(ContractIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_openActionPerformed

    private void ErasePopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErasePopupActionPerformed
        // TODO add your handling code here:
        Object[] options = {"Yes", "No"};
        boolean test = javax.swing.JOptionPane.showOptionDialog(
                this,
                "Do you want to delete this record?",
                title,
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[options.length - 1]) == javax.swing.JOptionPane.NO_OPTION;
        if (test) return;

        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.Statement stmt = jdbc.createStatement()) {
            int success = stmt.executeUpdate("DELETE FROM psnl.jobworker WHERE (uniqkey = '" + txtUniqueID.getText() + "')");
            if (success != 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Record erased.", title, javax.swing.JOptionPane.INFORMATION_MESSAGE);
                ClearPopupActionPerformed(evt);
            } else
                javax.swing.JOptionPane.showMessageDialog(this, "Record not erased.", title, javax.swing.JOptionPane.INFORMATION_MESSAGE);


        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(ContractIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_ErasePopupActionPerformed

    private void FileMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_FileMenuMenuSelected
        // TODO add your handling code here:
        ErasePopup.setEnabled(!txtUniqueID.getText().isEmpty());
    }//GEN-LAST:event_FileMenuMenuSelected

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        txtSearch.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
//                String text = txtSearch.getText();

//                if (text.trim().length() == 0) return;
                
//                Loading(text);
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
//                String text = txtSearch.getText();

//                if (text.trim().length() == 0) return;
                
//                Loading(text);
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
//                String text = txtSearch.getText();

//                if (text.trim().length() == 0) return;
                
//                Loading(text);
            }
            
            /*private void Loading(String value) {
                try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                        java.sql.Statement stmt = jdbc.createStatement();
                        java.sql.ResultSet rst = stmt.executeQuery(
                            "SELECT " +
                                "suffix, lastname, firstname, midname, uniqkey " +
                            "FROM " +
                                "psnl.contractual " +
                            "WHERE " +
                                "(UPPER(public.named(lastname, firstname, midname)) LIKE '%" + value.toUpperCase() + "%') " +
                            "ORDER BY " +
                                "lastname, firstname, midname")) {
                    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel)tblHuman.getModel();
                    model.setRowCount(0);
                    while (rst.next()) {
                        Object[] arData = {
                                    rst.getString(2) + " " + (rst.getString(1).trim().isEmpty() ? "" : rst.getString(1)),
                                    rst.getString(3),
                                    rst.getString(4),
                                    rst.getString(5)
                                    };
                        model.addRow(arData);
                    }


                } catch (java.sql.SQLException ex) {
                    javax.swing.JOptionPane.showMessageDialog(ContractIFrame.this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
                    java.util.logging.Logger.getLogger(ContractIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } finally {

                }
            }*/
        });
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.Statement stmt = jdbc.createStatement();
                java.sql.ResultSet rst = stmt.executeQuery("SELECT offcid, office FROM psnl.offices ORDER BY office")) {
            while (rst.next()) {
                arOffice.add(rst.getString(1));
                cboOffice.addItem(rst.getString(2));
            }


        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(ContractIFrame.this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(ContractIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void lookUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookUpActionPerformed
        // TODO add your handling code here:
        NamesDialog dialogo = new NamesDialog('C');
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
        if (dialogo.getUniqueID() != null) {
            txtUniqueID.setText(dialogo.getUniqueID());
            txtEmpID   .setText(dialogo.getEmpID());
            txtSurName .setText(dialogo.getSurName());
            txtGiveName.setText(dialogo.getFirstName());
            txtMidInit .setText(dialogo.getMidName());
            txtAddress .setText(dialogo.getAddress());
            cboSuffix  .setSelectedItem(dialogo.getSuffix());
            dtpBirthday.setDate(dialogo.getBirthDay());
            String test = dialogo.getBankAcct();
            if (test.isBlank())
                fmtAccount .setValue(null);
            else
                fmtAccount .setValue(test);
        }
        dialogo.dispose();
    }//GEN-LAST:event_lookUpActionPerformed

    private void lookposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookposActionPerformed
        // TODO add your handling code here:
        gov.entry.RankingDialog dialogo = new gov.entry.RankingDialog();
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
        if (dialogo.getRanking() != null) txtRanking.setText(dialogo.getRanking());
        dialogo.dispose();
    }//GEN-LAST:event_lookposActionPerformed

    private void btnFindfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindfindActionPerformed
        // TODO add your handling code here:
        String value = txtSearch.getText();
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
            java.sql.Statement stmt = jdbc.createStatement();
            java.sql.ResultSet rst = stmt.executeQuery(
                "SELECT " +
                    "suffix, lastname, firstname, midname, uniqkey " +
                "FROM " +
                    "psnl.jobworker " +
                "WHERE " +
                    "(UPPER(public.named(lastname, firstname, midname)) LIKE '%" + value.toUpperCase() + "%') AND (offcloc IS NOT NULL)" +
                "ORDER BY " +
                    "lastname, firstname, midname")) {
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel)tblHuman.getModel();
            model.setRowCount(0);
            while (rst.next()) {
                Object[] arData = {
                    rst.getString(2) + " " + (rst.getString(1).trim().isEmpty() ? "" : rst.getString(1)),
                    rst.getString(3),
                    rst.getString(4),
                    rst.getString(5)
                };
                model.addRow(arData);
            }

        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(ContractIFrame.this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(ContractIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_btnFindfindActionPerformed

    private void setNullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setNullActionPerformed
        // TODO add your handling code here:
        fmtAccount.setValue(null);
    }//GEN-LAST:event_setNullActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ErasePopup;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnLookPos;
    private javax.swing.JButton btnLookUp;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSetNull;
    private javax.swing.JComboBox<String> cboGender;
    private javax.swing.JComboBox<String> cboOffice;
    private javax.swing.JComboBox<String> cboSuffix;
    private com.toedter.calendar.JDateChooser dtpBirthday;
    private javax.swing.JFormattedTextField fmtAccount;
    private javax.swing.JFormattedTextField fmtRate;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tblHuman;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JTextField txtGiveName;
    private javax.swing.JTextField txtMidInit;
    private javax.swing.JTextField txtRanking;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSurName;
    private javax.swing.JTextField txtUniqueID;
    // End of variables declaration//GEN-END:variables

    private final boolean NUMERIC = true;
    private final boolean CONDITION = true;

}
