 package gov.cont;

/**
 *
 * @author USER
 */
public class COSFiltrateIFrame extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form COSFilteringIFrame
     */
    public COSFiltrateIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RowSorter = new javax.swing.table.TableRowSorter();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        tblCos = new javax.swing.JTable();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        txtFilter = new javax.swing.JTextField();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        setClosable(true);
        setTitle("Contractual Filtration");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/leaf.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "(✓)", "Lastname", "Firstname", "Middle Name", "keyuid"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tblCos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCos.setShowGrid(true);
        jScrollPane1.setViewportView(tblCos);
        if (tblCos.getColumnModel().getColumnCount() > 0) {
            tblCos.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblCos.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblCos.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblCos.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblCos.getColumnModel().getColumn(4).setMinWidth(0);
            tblCos.getColumnModel().getColumn(4).setPreferredWidth(0);
            tblCos.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 80, 616, 450));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("<html> Contractual Filtration → The process of excluding contracts that are inactive or no longer associated with the LGU. <br/> <b>Check the box below to remove contract-of-service personnel who are no longer employed in our LGU.</b> </html>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 620, -1));

        txtFilter.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/search.png"))); // NOI18N
        jLabel2.setText("Search");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 610, 36));

        setBounds(0, 0, 639, 571);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        RowSorter = new javax.swing.table.TableRowSorter<>(tblCos.getModel());
        tblCos.setRowSorter(RowSorter);
        
        try (java.sql.Connection jdbc = gov.hrisjo.PgDBcon.dbLink();
            java.sql.Statement stmt = jdbc.createStatement();
            java.sql.ResultSet rst = stmt.executeQuery(
                "SELECT " +
                    "phaseout, lastname, CONCAT(firstname, suffix), midname, uniqkey " +
                "FROM " +
                    "psnl.jobworker " +
                "WHERE " +
                    "(offcloc IS NOT NULL)" +
                "ORDER BY " +
                    "lastname, firstname, midname")) {
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel)tblCos.getModel();
            model.setRowCount(0);
            while (rst.next()) {
                Object[] arData = {
                    rst.getBoolean(1),
                    rst.getString(2),
                    rst.getString(3),
                    rst.getString(4),
                    rst.getString(5)
                };
                model.addRow(arData);
            }

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(COSFiltrateIFrame.this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(COSFiltrateIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {
            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }
        
        txtFilter.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {

            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent de) {
                String text = txtFilter.getText();
                if (text.trim().length() == 0) {
                    RowSorter.setRowFilter(null);
                } else {
                    RowSorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent de) {
                String text = txtFilter.getText();
                if (text.trim().length() == 0) {
                    RowSorter.setRowFilter(null);
                } else {
                    RowSorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent de) {

            }
        });
    }//GEN-LAST:event_formInternalFrameOpened

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try (java.sql.Connection jdbc = gov.hrisjo.PgDBcon.dbLink();
            java.sql.PreparedStatement stmt = jdbc.prepareStatement("UPDATE psnl.jobworker SET phaseout = ? WHERE uniqkey = ?;")) {
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel)tblCos.getModel();
            
            Short sized = (short)model.getRowCount();
            for (short abc = 0; abc < sized; abc++) {
                Boolean which = (Boolean)model.getValueAt(abc, 0);
                //if (!which) continue;
                
                String unique = (String)model.getValueAt(abc, 4);
                stmt.setBoolean(1, which);
                stmt.setString (2, unique);
                stmt.addBatch();
            }
            int[] test = stmt.executeBatch();
            if (test.length > 0)
                javax.swing.JOptionPane.showMessageDialog(this, "COS updated successfully!", title, javax.swing.JOptionPane.INFORMATION_MESSAGE);
            else
                javax.swing.JOptionPane.showMessageDialog(this, "COS failed to updated!", title, javax.swing.JOptionPane.WARNING_MESSAGE);

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(COSFiltrateIFrame.this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(COSFiltrateIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.table.TableRowSorter<javax.swing.table.TableModel> RowSorter;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTable tblCos;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
