package gov.cont;

/**
 *
 * @author felix
 */
public class NamesDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 9107879150458920067L;
    
    private char params = ' ';

    private final boolean NUMERIC = true;
    private final boolean CONDITION = true;

    private String Suffix, EmpID, SurName, FirstName, MidName, Address, BankAcct;
    private java.util.Date BirthDay = new java.util.Date();
    
    private final java.util.ArrayList<String> arUnique = new java.util.ArrayList<>();

    /**
     * Creates new form NamesDialog
     * @param passed
     */
    public NamesDialog(char passed) {
        super();
        initComponents();
        params = passed;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UniqueID = new java.lang.String();
        ListModelo = new javax.swing.DefaultListModel<>();
        okButton = new javax.swing.JButton();
        javax.swing.JButton cancelButton = new javax.swing.JButton();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        txtMidName = new javax.swing.JTextField();
        txtFirstname = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        cboSuffix = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        dtpBirth = new com.toedter.calendar.JDateChooser();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
        lstList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Look-Up Dialog");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/save.png"))); // NOI18N
        okButton.setText("Post/Save");
        okButton.setBorderPainted(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/cancel.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setBorderPainted(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        txtMidName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMidNameKeyTyped(evt);
            }
        });

        txtFirstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFirstnameKeyTyped(evt);
            }
        });

        txtSurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSurnameKeyTyped(evt);
            }
        });

        cboSuffix.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cboSuffix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "JR.", "JR. II", "SR.", "I", "II", "III", "IV", "V", "VI" }));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Suffix");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Last Name");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Mid Name");

        dtpBirth.setDateFormatString("MM/dd/yyyy");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Birthday");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane2.setViewportView(txtAddress);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Address");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtpBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFirstname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSurname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMidName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboSuffix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSuffix, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMidName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dtpBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lstList.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lstList.setModel(ListModelo);
        lstList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstList.setFocusable(false);
        jScrollPane3.setViewportView(lstList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtSurname.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtSurname.getText() + txtFirstname.getText() + txtMidName.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtSurname.getText() + txtFirstname.getText() + txtMidName.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtSurname.getText() + txtFirstname.getText() + txtMidName.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }
        });
        txtFirstname.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtSurname.getText() + txtFirstname.getText() + txtMidName.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtSurname.getText() + txtFirstname.getText() + txtMidName.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtSurname.getText() + txtFirstname.getText() + txtMidName.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }
        });
        txtMidName.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtSurname.getText() + txtFirstname.getText() + txtMidName.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtSurname.getText() + txtFirstname.getText() + txtMidName.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtSurname.getText() + txtFirstname.getText() + txtMidName.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }
        });
        
        lstList.addListSelectionListener((lste) -> {
            System.out.println(lste.getValueIsAdjusting());
            System.out.println(lste.getLastIndex());
        });
    }//GEN-LAST:event_formWindowOpened

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().equals("Retrieve")) {
            try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                    java.sql.PreparedStatement psmt = jdbc.prepareStatement(
                        "SELECT " +
                            "uniqkey, empid, suffix, lastname, firstname, midname, birthday, address, bank_acct " +
                        "FROM " +
                            "psnl.jobworker " +
                        "WHERE " +
                            "(uniqkey = ?)")) {
                int index = lstList.getSelectedIndex();
                psmt.setString(1, arUnique.get(index));
                try (java.sql.ResultSet rst = psmt.executeQuery()) {
                    if (rst.next()) {
                        UniqueID  = rst.getString(1);
                        EmpID     = rst.getString(2);
                        Suffix    = rst.getString(3);
                        SurName   = rst.getString(4);
                        FirstName = rst.getString(5);
                        MidName   = rst.getString(6);
                        BirthDay.setTime(rst.getDate(7).getTime());
                        Address   = rst.getString(8);
                        BankAcct  = (rst.getString(9) == null ? "" : rst.getString(9));
                    }
                }
                setVisible(false);
                
                    
            } catch (java.sql.SQLException exs) {
                javax.swing.JOptionPane.showMessageDialog(this, exs.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
                java.util.logging.Logger.getLogger(NamesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, exs);
            } finally {

            }
        } else {
            try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                    java.sql.PreparedStatement psmt = jdbc.prepareStatement("SELECT crypt(NOW()::VARCHAR, gen_salt('bf'));");
                    java.sql.PreparedStatement pzmt = jdbc.prepareStatement("SELECT DATE_PART('YEAR', NOW()) || 'J' || trim(to_char(NEXTVAL('psnl.jobseq'), '0000'))"); // FROM psnl.jobworker WHERE DATE_PART('YEAR', entered) = DATE_PART('YEAR', NOW())
                    java.sql.PreparedStatement pcmt = jdbc.prepareStatement("SELECT DATE_PART('YEAR', NOW()) || 'C' || trim(to_char(NEXTVAL('psnl.contra'), '0000'))"); // FROM psnl.jobworker WHERE DATE_PART('YEAR', entered) = DATE_PART('YEAR', NOW())
                    java.sql.Statement _smt = jdbc.createStatement()) {

                try (java.sql.ResultSet rst = psmt.executeQuery()) {
                    rst.next();
                    UniqueID  = rst.getString(1);
                }
                if (params == 'J') {
                    try (java.sql.ResultSet rst = pzmt.executeQuery()) {
                        rst.next();
                        EmpID = rst.getString(1);
                    }
                } else {
                    try (java.sql.ResultSet rst = pcmt.executeQuery()) {
                        rst.next();
                        EmpID = rst.getString(1);
                    }
                }
                SurName   = txtSurname.getText().trim();
                FirstName = txtFirstname.getText().trim();
                MidName   = txtMidName.getText().trim();
                Address   = txtAddress.getText();
                Suffix    = cboSuffix.getSelectedItem().toString();

                BirthDay.setTime(dtpBirth.getDate().getTime());
                String birthday = new java.text.SimpleDateFormat("yyyy-MM-dd").format(dtpBirth.getDate());

                dbase.SQLExecute saver = new dbase.SQLExecute("psnl.jobworker");
                saver.FieldName("uniqkey",   !NUMERIC, enums.Take.InsertOnly, CONDITION, UniqueID);
                saver.FieldName("empid",     !NUMERIC, enums.Take.InsertUpdate, EmpID);
                saver.FieldName("suffix",    !NUMERIC, enums.Take.InsertUpdate, Suffix);
                saver.FieldName("lastname",  !NUMERIC, enums.Take.InsertUpdate, SurName.toUpperCase());
                saver.FieldName("firstname", !NUMERIC, enums.Take.InsertUpdate, FirstName.toUpperCase());
                if (!MidName.isEmpty())
                    saver.FieldName("midname",   !NUMERIC, enums.Take.InsertUpdate, MidName.toUpperCase());
                if (!Address.isEmpty())
                    saver.FieldName("address",   !NUMERIC, enums.Take.InsertUpdate, Address);
                saver.FieldName("birthday",   !NUMERIC, enums.Take.InsertUpdate, birthday);
                _smt.executeUpdate(saver.Perform(enums.Fire.doInsert));

                setVisible(false);

            } catch (NullPointerException | java.sql.SQLException exs) {
                javax.swing.JOptionPane.showMessageDialog(this, exs.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
                java.util.logging.Logger.getLogger(NamesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, exs);
            } finally {

            }
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        UniqueID  = null;
        EmpID     = null;
        SurName   = null;
        FirstName = null;
        MidName   = null;
        Address   = null;
        Suffix    = null;
        BirthDay  = null;

        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void txtSurnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSurnameKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txtSurnameKeyTyped

    private void txtFirstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstnameKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txtFirstnameKeyTyped

    private void txtMidNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMidNameKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txtMidNameKeyTyped
            
    private void Loading(String text) {
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.PreparedStatement psmt = jdbc.prepareStatement(
                        "SELECT " +
                            "uniqkey, humane(lastname, firstname, suffix, midname), address " +
                        "FROM " +
                            "psnl.jobworker " +
                        "WHERE " +
                            "(UPPER(named(lastname, firstname, midname)) LIKE '%" + text.toUpperCase() + "%') " +
                        "ORDER BY " +
                            "lastname, firstname, midname");
                java.sql.ResultSet rst = psmt.executeQuery()) {
            ListModelo.clear(); arUnique.clear();
            while (rst.next()) {
                arUnique.add(rst.getString(1));
                ListModelo.addElement(rst.getString(2));
            }
            
            //okButton.setEnabled(ListModelo.isEmpty());
            
            okButton.setText(ListModelo.isEmpty() ? "Post/Save" : "Retrieve");


        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(NamesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.DefaultListModel<String> ListModelo;
    private java.lang.String UniqueID;
    private javax.swing.JComboBox<String> cboSuffix;
    private com.toedter.calendar.JDateChooser dtpBirth;
    private javax.swing.JList<String> lstList;
    private javax.swing.JButton okButton;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtMidName;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables

    
    public String getSurName() {return SurName;}

    public String getFirstName() {return FirstName;}

    public String getMidName() {return MidName;}

    public String getAddress() {return Address;}

    public String getUniqueID() {return UniqueID;}

    public String getEmpID() {return EmpID;}

    public String getSuffix() {return Suffix;}

    public java.util.Date getBirthDay() {return BirthDay;}

    public String getBankAcct() {return BankAcct;}
    
}
