/*
 * LoginDialog.java
 *
 * Created on June 6, 2007, 3:37 PM
 */

package gov.hrisjo;


/**
 *
 * @author  tigers
 */
public class LoginDialog extends javax.swing.JFrame implements java.awt.event.ActionListener, java.awt.event.KeyListener {

    private static final long serialVersionUID = 4798130067794136000L;

    /** Creates new form LoginDialog */
    public LoginDialog() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVerify = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnAbort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SYSTEM ACCESS SECURITY DIALOG");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/key.png")).getImage());
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnVerify.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVerify.setText("VERIFY");
        btnVerify.setBorderPainted(false);
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVerifyClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("USER I.D.");

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("PASSWORD");

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnAbort.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAbort.setText("ABORT");
        btnAbort.setBorderPainted(false);
        btnAbort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAbortClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(txtPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVerify)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(btnAbort)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnVerify)
                    .addComponent(btnAbort))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(304, 168));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        if (!verifyClicked)
            System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void ButtonVerifyClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVerifyClicked
        if (evt != null)
            return;

        boolean verified;
        try (java.sql.Connection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.PreparedStatement psmt = jdbc.prepareStatement(
                    "SELECT " +
                        "userdescrp, which, date_part('year', now()) " +
                    "FROM " +
                        "public.userlogon " +
                    "WHERE " +
                        "(userid = ?) AND " +
                        "(pazzword = CRYPT(?, pazzword))")) {
            //SELECT crypt('password', gen_salt('bf'))
            String usr = txtUser.getText(), pwd = String.valueOf(txtPassword.getPassword());
            psmt.setString(1, usr);
            psmt.setString(2, pwd);
            try (java.sql.ResultSet rst = psmt.executeQuery()) {
                if (rst.next()) {
                    System.setProperty("USERID",   txtUser.getText());
                    System.setProperty("USERNAME", rst.getString(1));
                    System.setProperty("ANIOS",    rst.getString(3));
                    verified = true;
                } else {
                    verified = false;
                    javax.swing.JOptionPane.showMessageDialog(this, "Invalid User/Password. Try again", getTitle(), javax.swing.JOptionPane.WARNING_MESSAGE);
                }
            }

            if (!verified) return;
            
            if (evt == null) { // if null it means keyboard event trigger
                //Gihemoan og condition kay kaduha man e trigger. Pagclick og pag Listen sa click sa mouse. Kun keyboard, kausa ra.
                dispose();
                verifyClicked = true;
                //SplashForm.main();
                MainJFrame.main();
            }
        } catch (java.sql.SQLException | NullPointerException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(this.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_ButtonVerifyClicked

    private void ButtonAbortClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAbortClicked
        // TODO add your handling code here:
        System.exit(0);
}//GEN-LAST:event_ButtonAbortClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtUser.addActionListener(this);
        txtUser.addKeyListener(this);

        txtPassword.addActionListener(this);
        txtPassword.addKeyListener(this);

        btnVerify.addActionListener(this);
        btnVerify.addKeyListener(this);

        btnAbort.addActionListener(this);
        btnAbort.addKeyListener(this);
    }//GEN-LAST:event_formWindowOpened

    public static void main(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Metal".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
////            com.formdev.flatlaf.FlatDarkLaf.setup();
            com.formdev.flatlaf.FlatLightLaf.setup();

//
//            javax.swing.plaf.metal. MetalLookAndFeel.setCurrentTheme(new javax.swing.plaf.metal.OceanTheme());
//            javax.swing.UIManager.setLookAndFeel(new javax.swing.plaf.metal.MetalLookAndFeel());
//
//        } catch (javax.swing.UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        try {
//            // Set the custom Dark Metal theme
//            //javax.swing.plaf.metal.MetalLookAndFeel.setCurrentTheme(new themes.DarkMetalTheme());
//            
//            // Apply the Metal Look and Feel
//            javax.swing.UIManager.setLookAndFeel(new javax.swing.plaf.metal.MetalLookAndFeel());
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        
        java.awt.EventQueue.invokeLater(() -> {
            new LoginDialog().setVisible(true); //new javax.swing.JFrame(), true
        });

        //handle = new ConnectionHandler(); //, args[2]);
        //RotateBits rotate = new RotateBits();
    }

    @Override
    public void keyTyped(java.awt.event.KeyEvent e) {
        //JOptionPane.showMessageDialog(this, e.getKeyText(e.getKeyCode()), "keyTyped", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void keyPressed(java.awt.event.KeyEvent e) {
        //JOptionPane.showMessageDialog(this, String.valueOf(e.getKeyCode()), "keyPressed", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void keyReleased(java.awt.event.KeyEvent e) {
        if (e.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) ButtonAbortClicked(null);
    }

    @Override
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        //JOptionPane.showMessageDialog(this, e.getActionCommand(), "actionPerformed", JOptionPane.ERROR_MESSAGE);
        if (evt.getSource().equals(txtUser))
            txtPassword.requestFocus();
        
        else if (!evt.getSource().equals(btnAbort))
            ButtonVerifyClicked(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbort;
    private javax.swing.JButton btnVerify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    private boolean verifyClicked = false;
    
}
