/*
 * MainJFrame.java
 *
 * Created on February 28, 2008, 11:26 AM
 */

package gov.hrisjo;

/**
 * 
 * @author  felixiong
 */
public class MainJFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 1788798056219129871L;
    
    private gov.entry.JobOrderIFrame            jobworkers;
    private gov.cont .ContractIFrame            contWorker;
    private gov.trans.CreatorJFrame             createJob;
    
    private gov.reports.HistoryIFrame           listJob;
    private gov.reports.SummarizeJFrame         sumAllJob;
    private gov.reports.SummaryJFrame           summaryJob;
    private gov.reports.ActualResultJFrame      actualCount;
    private gov.reports.MasterlistJIFrame       masterList;
    private gov.reports.UnservedRpt             unserveList;
    private gov.reports.JosCosWageJFrame        joscosWage;
    
    private gov.admin.CreateUserJFrame          createUser;
    private gov.admin.EraseUserJFrame           removeUser;
    
    private gov.find.LocateFrame                findForm;
    private gov.find.ConsolidateFrame           consolForm;


    {
        setExtendedState(getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /** Creates new form MainForm */
    public MainJFrame() {
        initComponents();
        //setSize(java.awt.Toolkit.getDefaultToolkit().getScreenSize());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PetsaRon = new java.util.Date();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        mdiDesktopPane = new mdiMenu.MDIDesktopPane();
        javax.swing.JToolBar jToolBar1 = new javax.swing.JToolBar();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JToolBar.Separator jSeparator5 = new javax.swing.JToolBar.Separator();
        txtDateNow = new javax.swing.JTextField();
        javax.swing.JToolBar.Separator jSeparator6 = new javax.swing.JToolBar.Separator();
        javax.swing.JToolBar.Separator jSeparator7 = new javax.swing.JToolBar.Separator();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JToolBar.Separator jSeparator8 = new javax.swing.JToolBar.Separator();
        txtWhoIam = new javax.swing.JTextField();
        toggleTheme = new javax.swing.JToggleButton();
        javax.swing.JMenuBar MenuBar = new javax.swing.JMenuBar();
        mnuEntries = new javax.swing.JMenu();
        EmployeePopup = new javax.swing.JMenuItem();
        CreateJobItem = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ContractItem = new javax.swing.JMenuItem();
        AdminMenu = new javax.swing.JMenu();
        ManageUserMenu = new javax.swing.JMenu();
        CreateUserItem = new javax.swing.JMenuItem();
        EraseUserItem = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ProjectItem = new javax.swing.JMenuItem();
        LocateItem = new javax.swing.JMenuItem();
        ConsolidateItem = new javax.swing.JMenuItem();
        javax.swing.JMenu mnuSystem = new javax.swing.JMenu();
        javax.swing.JMenuItem HistoryItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem SummarizeItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem SummaryItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem NewJOListItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem ActualCountItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem UnservedItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem DumlaoWageItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem MasterListItem = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator3 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenuItem popQuit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JOB ORDER & CONTRACTUAL MONITORING");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/hrd.gif")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                WindowOpened(evt);
            }
        });

        jScrollPane1.setViewportView(mdiDesktopPane);

        jToolBar1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("TODAY'S DATE");
        jToolBar1.add(jLabel1);
        jToolBar1.add(jSeparator5);

        txtDateNow.setEditable(false);
        jToolBar1.add(txtDateNow);
        jToolBar1.add(jSeparator6);
        jToolBar1.add(jSeparator7);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("ACTIVE USER");
        jToolBar1.add(jLabel2);
        jToolBar1.add(jSeparator8);

        txtWhoIam.setEditable(false);
        jToolBar1.add(txtWhoIam);

        toggleTheme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/moon.png"))); // NOI18N
        toggleTheme.setFocusable(false);
        toggleTheme.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toggleTheme.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/sun.png"))); // NOI18N
        toggleTheme.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toggleTheme.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                toggleThemeItemStateChanged(evt);
            }
        });
        jToolBar1.add(toggleTheme);

        mnuEntries.setText("ENTRIES");

        EmployeePopup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/leaf.png"))); // NOI18N
        EmployeePopup.setText("Job Order's Information");
        EmployeePopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeePopupAction(evt);
            }
        });
        mnuEntries.add(EmployeePopup);

        CreateJobItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/leaf.png"))); // NOI18N
        CreateJobItem.setText("Create Job Order");
        CreateJobItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateJobItemActionPerformed(evt);
            }
        });
        mnuEntries.add(CreateJobItem);
        mnuEntries.add(jSeparator2);

        ContractItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/leaf.png"))); // NOI18N
        ContractItem.setText("Contractual Information");
        ContractItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContractItemActionPerformed(evt);
            }
        });
        mnuEntries.add(ContractItem);

        MenuBar.add(mnuEntries);

        AdminMenu.setText("ADMINISTER");
        AdminMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                AdminMenuMenuSelected(evt);
            }
        });

        ManageUserMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/maange.png"))); // NOI18N
        ManageUserMenu.setText("Manage User");

        CreateUserItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/leaf.png"))); // NOI18N
        CreateUserItem.setText("Create User");
        CreateUserItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateUserItemAction(evt);
            }
        });
        ManageUserMenu.add(CreateUserItem);

        EraseUserItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/leaf.png"))); // NOI18N
        EraseUserItem.setText("Remove User");
        EraseUserItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EraseUserItemAction(evt);
            }
        });
        ManageUserMenu.add(EraseUserItem);

        AdminMenu.add(ManageUserMenu);
        AdminMenu.add(jSeparator1);

        ProjectItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/leaf.png"))); // NOI18N
        ProjectItem.setText("CREATE PROJECT 2012");
        ProjectItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProjectItemAction(evt);
            }
        });
        AdminMenu.add(ProjectItem);

        LocateItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/leaf.png"))); // NOI18N
        LocateItem.setText("Search/Locate");
        LocateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocateItemAction(evt);
            }
        });
        AdminMenu.add(LocateItem);

        ConsolidateItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/consolidate.png"))); // NOI18N
        ConsolidateItem.setText("Payroll Consolidation");
        ConsolidateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consolidateItemAction(evt);
            }
        });
        AdminMenu.add(ConsolidateItem);

        MenuBar.add(AdminMenu);

        mnuSystem.setText("SYSTEM");

        HistoryItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/history.png"))); // NOI18N
        HistoryItem.setMnemonic('Q');
        HistoryItem.setText("History");
        HistoryItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryItemAction(evt);
            }
        });
        mnuSystem.add(HistoryItem);

        SummarizeItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/report.png"))); // NOI18N
        SummarizeItem.setMnemonic('Q');
        SummarizeItem.setText("Summarize");
        SummarizeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SummarizeItemAction(evt);
            }
        });
        mnuSystem.add(SummarizeItem);

        SummaryItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/report.png"))); // NOI18N
        SummaryItem.setMnemonic('Q');
        SummaryItem.setText("Summary");
        SummaryItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SummaryItemAction(evt);
            }
        });
        mnuSystem.add(SummaryItem);

        NewJOListItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/report.png"))); // NOI18N
        NewJOListItem.setMnemonic('Q');
        NewJOListItem.setText("New JO Listing");
        NewJOListItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewJOListItemAction(evt);
            }
        });
        mnuSystem.add(NewJOListItem);

        ActualCountItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/report.png"))); // NOI18N
        ActualCountItem.setMnemonic('Q');
        ActualCountItem.setText("Actual JO/Endo Count");
        ActualCountItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualCountItemAction(evt);
            }
        });
        mnuSystem.add(ActualCountItem);

        UnservedItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/report.png"))); // NOI18N
        UnservedItem.setMnemonic('Q');
        UnservedItem.setText("Unserved J.O.");
        UnservedItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnservedItemAction(evt);
            }
        });
        mnuSystem.add(UnservedItem);

        DumlaoWageItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/report.png"))); // NOI18N
        DumlaoWageItem.setMnemonic('Q');
        DumlaoWageItem.setText("JOs & COS Nakasweldo");
        DumlaoWageItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DumlaoWageItemAction(evt);
            }
        });
        mnuSystem.add(DumlaoWageItem);

        MasterListItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/report.png"))); // NOI18N
        MasterListItem.setMnemonic('Q');
        MasterListItem.setText("Master List");
        MasterListItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasterListItemAction(evt);
            }
        });
        mnuSystem.add(MasterListItem);
        mnuSystem.add(jSeparator3);

        popQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        popQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/quit.png"))); // NOI18N
        popQuit.setMnemonic('Q');
        popQuit.setText("Quit");
        popQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popQuitAction(evt);
            }
        });
        mnuSystem.add(popQuit);

        MenuBar.add(mnuSystem);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeePopupAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeePopupAction
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        if (jobworkers == null || jobworkers.isClosed()) {
            jobworkers = new gov.entry.JobOrderIFrame();
            mdiDesktopPane.add(jobworkers);
            jobworkers.setVisible(true);
        } else
            jobworkers.setVisible(true);
    }//GEN-LAST:event_EmployeePopupAction

    private void popQuitAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popQuitAction
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        dispatchEvent(new java.awt.event.WindowEvent(this, java.awt.event.WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_popQuitAction

    private void WindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_WindowOpened
        if (evt.getID() == 0) return;
        setExtendedState(getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
        try (java.sql.Connection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.Statement stmt = jdbc.createStatement();
                java.sql.ResultSet rst = stmt.executeQuery(
                        "SELECT " +
                            "COUNT(*), " +
                            "DATE_PART('YEAR', NOW())::SMALLINT, " +
                            "NOW()::TIMESTAMP WITHOUT TIME ZONE " +
                        "FROM " +
                            "cbo.projects " +
                        "WHERE " +
                            "(atyear = DATE_PART('YEAR', NOW())::SMALLINT)");
                java.sql.PreparedStatement psmt = jdbc.prepareStatement("INSERT INTO " +
                        "cbo.projects " +
                    "SELECT " +
                        "DATE_PART('YEAR', NOW()) || SUBSTRING(projid, 5, 6), " +
                        "projtitle, 0.0, '" + System.getProperty("USERID") + "', DATE_PART('YEAR', NOW())::SMALLINT, offcloc " +
                    "FROM " +
                        "cbo.projects " +
                    "WHERE " +
                        "(approp <> 0) AND " +
                        "(atyear = (DATE_PART('YEAR', NOW()) - 1))" +
                    "ORDER BY " +
                        "projid");
                java.sql.PreparedStatement pzmt = jdbc.prepareStatement("UPDATE cbo.parameters SET present = DATE_PART('YEAR', NOW())::SMALLINT")) {
            if (rst.next()) {
                if (rst.getShort(1) == 0) {
                    psmt.executeUpdate();
                    pzmt.executeUpdate();
                }
                if (System.getProperty("ACCESS") != null) System.setProperty("ANIOS", rst.getString(2));
                txtDateNow.setText(new java.text.SimpleDateFormat("MMMM dd, yyyy").format(rst.getDate(3)));
                //String petsa =
                PetsaRon = rst.getDate(3);
            }
            mnuEntries     .setVisible(System.getProperty("ACCESS") == null);
            ManageUserMenu .setVisible(System.getProperty("ACCESS") == null);
            ProjectItem    .setVisible(System.getProperty("ACCESS") == null);
            ConsolidateItem.setVisible(System.getProperty("ACCESS") == null);



        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {
            txtWhoIam.setText(System.getProperty("USERNAME"));
            
            ProjectItem.setVisible(false);
        }
    }//GEN-LAST:event_WindowOpened

    private void CreateUserItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateUserItemAction
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        if (createUser == null || createUser.isClosed()) {
            createUser = new gov.admin.CreateUserJFrame();
            mdiDesktopPane.add(createUser);
            createUser.setVisible(true);
        } else
            createUser.setVisible(true);
    }//GEN-LAST:event_CreateUserItemAction

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (evt.getID() == 0) return;
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void ProjectItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProjectItemAction
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
//        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
//                java.sql.PreparedStatement psmt = jdbc.prepareStatement("INSERT INTO " +
//                        "cbo.projects " +
//                    "SELECT " +
//                        "DATE_PART('YEAR', NOW()) || SUBSTRING(projid, 5, 6), " +
//                        "projtitle, 0.0, '" + System.getProperty("USERID") + "', DATE_PART('YEAR', NOW())::SMALLINT, offcloc " +
//                    "FROM " +
//                        "cbo.projects " +
//                    "WHERE " +
//                        "(atyear = (DATE_PART('YEAR', NOW()) - 1))" +
//                    "ORDER BY " +
//                        "projid");
//                java.sql.PreparedStatement pzmt = jdbc.prepareStatement("UPDATE cbo.parameters SET present = DATE_PART('YEAR', NOW())::SMALLINT")) {
//            psmt.executeUpdate();
//            pzmt.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "New Project batch created.", getTitle(), javax.swing.JOptionPane.INFORMATION_MESSAGE);
//
//
//        } catch (java.sql.SQLException ex) {
//            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
//            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } finally {
//
//        }
    }//GEN-LAST:event_ProjectItemAction

    private void AdminMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_AdminMenuMenuSelected
        // TODO add your handling code here:
        boolean test = evt.getSource().toString().isBlank() | evt.getSource().toString().isEmpty();
        if (test) return;
        System.out.println(test);
//        try (java.sql.Connection jdbc = new gov.hrisjo.PGdbLink();
//                java.sql.Statement stmt = jdbc.createStatement();
//                java.sql.ResultSet rst = stmt.executeQuery(
//                        "SELECT " +
//                            "COUNT(*), " +
//                            "DATE_PART('YEAR', NOW())::SMALLINT " +
//                        "FROM " +
//                            "cbo.projects " +
//                        "WHERE " +
//                            "(atyear = DATE_PART('YEAR', NOW())::SMALLINT)")) {
//            if (rst.next()) {
//                ProjectItem.setEnabled(rst.getShort(1) == 0);
//                ProjectItem.setText("CREATE PROJECT " + rst.getShort(2));
//            }
//
//        } catch (java.sql.SQLException ex) {
//            javax.swing.JOptionPane.showMessageDialog(this, "ex.getMessage()", getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
//            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } finally {
//
//        }
    }//GEN-LAST:event_AdminMenuMenuSelected

    private void CreateJobItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateJobItemActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        if (createJob == null || createJob.isClosed()) {
            createJob = new gov.trans.CreatorJFrame();
            mdiDesktopPane.add(createJob);
            createJob.setVisible(true);
        } else
            createJob.setVisible(true);
    }//GEN-LAST:event_CreateJobItemActionPerformed

    private void ContractItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContractItemActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        if (contWorker == null || contWorker.isClosed()) {
            contWorker = new gov.cont.ContractIFrame();
            mdiDesktopPane.add(contWorker);
            contWorker.setVisible(true);
        } else
            contWorker.setVisible(true);
    }//GEN-LAST:event_ContractItemActionPerformed

    private void EraseUserItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EraseUserItemAction
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        if (removeUser == null || removeUser.isClosed()) {
            removeUser = new gov.admin.EraseUserJFrame();
            mdiDesktopPane.add(removeUser);
            removeUser.setVisible(true);
        } else
            removeUser.setVisible(true);
    }//GEN-LAST:event_EraseUserItemAction

    private void HistoryItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryItemAction
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        if (listJob == null || listJob.isClosed()) {
            listJob = new gov.reports.HistoryIFrame();
            mdiDesktopPane.add(listJob);
            listJob.setVisible(true);
        } else
            listJob.setVisible(true);
    }//GEN-LAST:event_HistoryItemAction

    private void SummarizeItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SummarizeItemAction
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        if (sumAllJob == null || sumAllJob.isClosed()) {
            sumAllJob = new gov.reports.SummarizeJFrame();
            mdiDesktopPane.add(sumAllJob);
            sumAllJob.setVisible(true);
        } else
            sumAllJob.setVisible(true);
    }//GEN-LAST:event_SummarizeItemAction

    private void LocateItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocateItemAction
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        if (findForm == null || findForm.isClosed()) {
            findForm = new gov.find.LocateFrame();
            mdiDesktopPane.add(findForm);
            findForm.setVisible(true);
        } else
            findForm.setVisible(true);
    }//GEN-LAST:event_LocateItemAction

    private void SummaryItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SummaryItemAction
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        if (summaryJob == null || summaryJob.isClosed()) {
            summaryJob = new gov.reports.SummaryJFrame();
            mdiDesktopPane.add(summaryJob);
            summaryJob.setVisible(true);
        } else
            summaryJob.setVisible(true);
    }//GEN-LAST:event_SummaryItemAction

    private void NewJOListItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewJOListItemAction
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        java.io.InputStream reportSource = getClass().getResourceAsStream("/jreport/newJOlist.jasper");

        java.util.Calendar cald = java.util.Calendar.getInstance();

//        org.apache.log4j.Logger logger = org.apache.log4j.Logger.getRootLogger();
//        logger.setLevel(org.apache.log4j.Level.WARN);
        
        try (java.sql.Connection jdbc = new gov.hrisjo.PGdbLink()) {
            Object retVal = javax.swing.JOptionPane.showInputDialog(this, "Please enter your desired YEAR.", getTitle(), javax.swing.JOptionPane.PLAIN_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/voucher.png")), null, cald.get(java.util.Calendar.YEAR));
            if (retVal == null) return;
            if (retVal.equals("")) return;
            if (!retVal.toString().matches("\\d+")) return;
//            
//            // REPORT PARAMETERS
            java.util.Map<String, Object> params = new java.util.HashMap<>();
            params.put("YearNow", Short.valueOf(retVal.toString(), 10));

            net.sf.jasperreports.engine.JasperPrint jasperPrint = net.sf.jasperreports.engine.JasperFillManager.fillReport(reportSource, params, jdbc);
            net.sf.jasperreports.view.JasperViewer.viewReport(jasperPrint, false);



        } catch (java.awt.HeadlessException | NumberFormatException | java.sql.SQLException | net.sf.jasperreports.engine.JRException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_NewJOListItemAction

    private void ActualCountItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualCountItemAction
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        if (actualCount == null || actualCount.isClosed()) {
            actualCount = new gov.reports.ActualResultJFrame();
            mdiDesktopPane.add(actualCount);
            actualCount.setVisible(true);
        } else
            actualCount.setVisible(true);
    }//GEN-LAST:event_ActualCountItemAction

    private void MasterListItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasterListItemAction
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        if (masterList == null || masterList.isClosed()) {
            masterList = new gov.reports.MasterlistJIFrame();
            mdiDesktopPane.add(masterList);
            masterList.setVisible(true);
        } else
            masterList.setVisible(true);
    }//GEN-LAST:event_MasterListItemAction

    private void consolidateItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consolidateItemAction
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        if (consolForm == null || consolForm.isClosed()) {
            consolForm = new gov.find.ConsolidateFrame();
            mdiDesktopPane.add(consolForm);
            consolForm.setVisible(true);
        } else
            consolForm.setVisible(true);
    }//GEN-LAST:event_consolidateItemAction

    private void UnservedItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnservedItemAction
        // TODO add your handling code here:
        if (evt.getID() == Integer.MIN_VALUE | evt.getID() == Integer.MIN_VALUE) return;
        if (unserveList == null || unserveList.isClosed()) {
            unserveList = new gov.reports.UnservedRpt();
            mdiDesktopPane.add(unserveList);
            unserveList.setVisible(true);
        } else
            unserveList.setVisible(true);
    }//GEN-LAST:event_UnservedItemAction

    private void DumlaoWageItemAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DumlaoWageItemAction
        // TODO add your handling code here:
        if (evt.getID() == Integer.MIN_VALUE | evt.getID() == Integer.MIN_VALUE) return;
        if (joscosWage == null || joscosWage.isClosed()) {
            joscosWage = new gov.reports.JosCosWageJFrame();
            mdiDesktopPane.add(joscosWage);
            joscosWage.setVisible(true);
        } else
            joscosWage.setVisible(true);
    }//GEN-LAST:event_DumlaoWageItemAction

    private void toggleThemeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_toggleThemeItemStateChanged
        // TODO add your handling code here:
        try {
            if(evt.getStateChange()==1) 
                javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatDarkLaf());
            else 
                javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_toggleThemeItemStateChanged

    public static void main() {
        java.awt.EventQueue.invokeLater(() -> {
            new MainJFrame().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AdminMenu;
    private javax.swing.JMenuItem ConsolidateItem;
    private javax.swing.JMenuItem ContractItem;
    private javax.swing.JMenuItem CreateJobItem;
    private javax.swing.JMenuItem CreateUserItem;
    private javax.swing.JMenuItem EmployeePopup;
    private javax.swing.JMenuItem EraseUserItem;
    private javax.swing.JMenuItem LocateItem;
    private javax.swing.JMenu ManageUserMenu;
    private static java.util.Date PetsaRon;
    private javax.swing.JMenuItem ProjectItem;
    private mdiMenu.MDIDesktopPane mdiDesktopPane;
    private javax.swing.JMenu mnuEntries;
    private javax.swing.JToggleButton toggleTheme;
    private javax.swing.JTextField txtDateNow;
    private javax.swing.JTextField txtWhoIam;
    // End of variables declaration//GEN-END:variables

    public static java.util.Date getPetsaRon() {return PetsaRon;}
    
}
