package gov.entry;

/**
 *
 * @author felix
 */
public class RankingDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 3037402292435857994L;

    private final boolean NUMERIC = true;
    private final boolean CONDITION = true;

    private final java.util.List<Short> arUnique = new java.util.ArrayList<>();

    private Short UniqueID;
    /**
     * Creates new form NamesDialog
     */
    public RankingDialog() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListModelo = new javax.swing.DefaultListModel<>();
        okButton = new javax.swing.JButton();
        javax.swing.JButton cancelButton = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
        lstList = new javax.swing.JList<>();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        txtRank = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Look-Up Dialog");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/save.png"))); // NOI18N
        okButton.setText("Post/Save");
        okButton.setBorderPainted(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/cancel.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setBorderPainted(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        lstList.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lstList.setModel(ListModelo);
        lstList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstList.setFocusable(false);
        jScrollPane3.setViewportView(lstList);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Designation");

        txtRank.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRankKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRank, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtRank.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtRank.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtRank.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtRank.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }
        });

        lstList.addListSelectionListener((lste) -> {
            System.out.println(lste.getValueIsAdjusting());
            System.out.println(lste.getLastIndex());
        });
    }//GEN-LAST:event_formWindowOpened

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().equals("Retrieve")) {
            try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                    java.sql.PreparedStatement psmt = jdbc.prepareStatement("SELECT pos_id, ranking FROM psnl.designation WHERE (pos_id = ?)")) {
                int index = lstList.getSelectedIndex();
                psmt.setShort(1, arUnique.get(index));
                try (java.sql.ResultSet rst = psmt.executeQuery()) {
                    if (rst.next()) {
                        UniqueID  = rst.getShort(1);
                        txtRank.setText(rst.getString(2));
                    }
                }
                setVisible(false);
                
                    
            } catch (java.sql.SQLException exs) {
                javax.swing.JOptionPane.showMessageDialog(this, exs.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
                java.util.logging.Logger.getLogger(RankingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, exs);
            } finally {

            }
        } else {
            try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                    java.sql.Statement _smt = jdbc.createStatement()) {

                dbase.SQLExecute saver = new dbase.SQLExecute("psnl.designation");
                saver.FieldName("pos_id",   NUMERIC, enums.Take.ConditionOnly, UniqueID);
                saver.FieldName("ranking", !NUMERIC, enums.Take.InsertUpdate,  txtRank.getText());
                _smt.executeUpdate(saver.Perform(enums.Fire.doInsert));

                setVisible(false);

            } catch (NullPointerException | java.sql.SQLException exs) {
                javax.swing.JOptionPane.showMessageDialog(this, exs.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
                java.util.logging.Logger.getLogger(RankingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, exs);
            } finally {

            }
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        UniqueID = null;
        txtRank.setText(null);

        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void txtRankKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRankKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txtRankKeyTyped
            
    private void Loading(String text) {
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.PreparedStatement psmt = jdbc.prepareStatement(
                        "SELECT pos_id, ranking FROM psnl.designation WHERE (UPPER(ranking) LIKE '%" + text.toUpperCase() + "%') ORDER BY ranking");
                java.sql.ResultSet rst = psmt.executeQuery()) {
            ListModelo.clear(); arUnique.clear();
            while (rst.next()) {
                arUnique.add(rst.getShort(1));
                ListModelo.addElement(rst.getString(2));
            }
            okButton.setText(ListModelo.isEmpty() ? "Post/Save" : "Retrieve");


        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(RankingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.DefaultListModel<String> ListModelo;
    private javax.swing.JList<String> lstList;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField txtRank;
    // End of variables declaration//GEN-END:variables

    
    public Short getUniqueID() {return UniqueID;}

    public String getRanking() {return txtRank.getText();}
    
}
