package gov.trans;

/**
 *
 * @author felix
 */
public class NamesDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = -5355959677339157931L;

    private final java.util.List<String> arUnique = new java.util.ArrayList<>();
    
    private Double PayRate;
    private Integer Counts;

    /**
     * Creates new form NamesDialog
     */
    public NamesDialog() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UniqueID = new java.lang.String();
        ListModelo = new javax.swing.DefaultListModel<>();
        Pangalan = new java.lang.String();
        EmpID = new java.lang.String();
        Ranggo = new java.lang.String();
        okButton = new javax.swing.JButton();
        javax.swing.JButton cancelButton = new javax.swing.JButton();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        txtMidName = new javax.swing.JTextField();
        txtFirstname = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
        lstList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Look-Up Dialog");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/selection-row.png"))); // NOI18N
        okButton.setText("Select");
        okButton.setBorderPainted(false);
        okButton.setEnabled(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/cancel.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setBorderPainted(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        txtMidName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMidNameKeyTyped(evt);
            }
        });

        txtFirstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFirstnameKeyTyped(evt);
            }
        });

        txtSurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSurnameKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Last Name");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Mid Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSurname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMidName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMidName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lstList.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lstList.setModel(ListModelo);
        lstList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstList.setFocusable(false);
        jScrollPane3.setViewportView(lstList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtSurname.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtSurname.getText() + txtFirstname.getText() + txtMidName.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtSurname.getText() + txtFirstname.getText() + txtMidName.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtSurname.getText() + txtFirstname.getText() + txtMidName.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }
        });
        txtFirstname.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtSurname.getText() + txtFirstname.getText() + txtMidName.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtSurname.getText() + txtFirstname.getText() + txtMidName.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtSurname.getText() + txtFirstname.getText() + txtMidName.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }
        });
        txtMidName.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtSurname.getText() + txtFirstname.getText() + txtMidName.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtSurname.getText() + txtFirstname.getText() + txtMidName.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                String text = txtSurname.getText() + txtFirstname.getText() + txtMidName.getText();
                if (text.trim().length() == 0) return;
                Loading(text);
            }
        });
        
        lstList.addListSelectionListener((lste) -> {
            System.out.println(lste.getValueIsAdjusting());
            System.out.println(lste.getLastIndex());
            okButton.setEnabled(lstList.getSelectedIndex() >= 0);
        });
    }//GEN-LAST:event_formWindowOpened

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.PreparedStatement psmt = jdbc.prepareStatement(
                    "SELECT " +
                        "uniqkey, empid, humane(lastname, firstname, suffix, midname), jobdesc, payrate, " +
                        "(SELECT COUNT(*) FROM cbo.jobarrange WHERE (empkey = uniqkey)) " +
                    "FROM " +
                        "psnl.jobworker " +
                    "WHERE " +
                        "(uniqkey = ?)")) {
            int index = lstList.getSelectedIndex();
            psmt.setString(1, arUnique.get(index));
            try (java.sql.ResultSet rst = psmt.executeQuery()) {
                if (rst.next()) {
                    UniqueID  = rst.getString(1);
                    EmpID     = rst.getString(2);
                    Pangalan  = rst.getString(3);
                    Ranggo    = rst.getString(4);
                    PayRate   = rst.getDouble(5);
                    Counts    = rst.getInt(6);
                }
            }
            setVisible(false);


        } catch (java.sql.SQLException exs) {
            javax.swing.JOptionPane.showMessageDialog(this, exs.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(NamesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, exs);
        } finally {

        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        UniqueID  = null;
        EmpID     = null;
        Pangalan  = null;
        PayRate   = null;

        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void txtSurnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSurnameKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txtSurnameKeyTyped

    private void txtFirstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstnameKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txtFirstnameKeyTyped

    private void txtMidNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMidNameKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txtMidNameKeyTyped

    private void Loading(String text) {
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.PreparedStatement psmt = jdbc.prepareStatement(
                        "SELECT " +
                            "uniqkey, humane(lastname, firstname, suffix, midname), address " +
                        "FROM " +
                            "psnl.jobworker " +
                        "WHERE " +
                            "(UPPER(named(lastname, firstname, midname)) LIKE '%" + text.toUpperCase() + "%') AND (offcloc IS NULL) " +
                        "ORDER BY " +
                            "lastname, firstname, midname");
                java.sql.ResultSet rst = psmt.executeQuery()) {
            ListModelo.clear(); arUnique.clear();
            while (rst.next()) {
                arUnique.add(rst.getString(1));
                ListModelo.addElement(rst.getString(2));
            }
            
            //okButton.setEnabled(ListModelo.isEmpty());
            
//            okButton.setText(ListModelo.isEmpty() ? "Post/Save" : "Retrieve");


        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(NamesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.lang.String EmpID;
    private javax.swing.DefaultListModel<String> ListModelo;
    private java.lang.String Pangalan;
    private java.lang.String Ranggo;
    private java.lang.String UniqueID;
    private javax.swing.JList<String> lstList;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtMidName;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables

    public String getPangalan() {return Pangalan;}

    public String getUniqueID() {return UniqueID;}

    public String getEmpID()    {return EmpID;}

    public String getRanggo()   {return Ranggo;}

    public Double getPayRate()  {return PayRate;}

    public Integer getCounts() {return Counts;}

}
