/*
 * CreateUserJFrame.java
 *
 * Created on December 16, 2008, 1:57 PM
 */

package gov.admin;

/**
 *
 * @author  felixiong
 */
public class CreateUserJFrame extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = -1396261292250746260L;

    private final java.util.ArrayList<UserLogon> LogList = new java.util.ArrayList<>();
    private final java.util.ArrayList<javax.swing.JCheckBox> checkBoxes = new java.util.ArrayList<>();
    

    /** Creates new form MngUserIFrm */
    @SuppressWarnings("this-escape")
    public CreateUserJFrame() {initComponents();}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JTabbedPane jTabbedPane1 = new javax.swing.JTabbedPane();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        pwdPassword = new javax.swing.JPasswordField();
        cboUserID = new organize.JComboDynamicWidth<>();
        txtUserName = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        CheckBox1 = new javax.swing.JCheckBox();
        CheckBox2 = new javax.swing.JCheckBox();
        CheckBox3 = new javax.swing.JCheckBox();
        javax.swing.JSeparator jSeparator3 = new javax.swing.JSeparator();
        CheckBox4 = new javax.swing.JCheckBox();
        CheckBox5 = new javax.swing.JCheckBox();
        javax.swing.JToolBar jToolBar1 = new javax.swing.JToolBar();
        javax.swing.JButton cmdClear = new javax.swing.JButton();
        javax.swing.JButton cmdSave = new javax.swing.JButton();
        javax.swing.JToolBar.Separator jSeparator1 = new javax.swing.JToolBar.Separator();
        javax.swing.JToolBar.Separator jSeparator2 = new javax.swing.JToolBar.Separator();
        javax.swing.JButton cmdClose = new javax.swing.JButton();
        javax.swing.JMenuBar MenuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu FileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem SaveItem = new javax.swing.JMenuItem();
        javax.swing.JMenu FormMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem CloseItem = new javax.swing.JMenuItem();

        setClosable(true);
        setTitle("MANAGE USER ACCESS RIGHTS");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/leaf.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                InternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("USER ID");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("PASSWORD");

        cboUserID.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cboUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUserIDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("USER NAME");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Permission Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        CheckBox1.setText("Job Order's Information");

        CheckBox2.setText("Create Job Order");

        CheckBox3.setText("Contractual Information");

        CheckBox4.setText("Manage User");

        CheckBox5.setText("Payroll Consolidation");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckBox1)
                            .addComponent(CheckBox2)
                            .addComponent(CheckBox3)
                            .addComponent(CheckBox4)
                            .addComponent(CheckBox5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBox5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwdPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(txtUserName)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtUserID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("USER", jPanel1);

        jToolBar1.setRollover(true);

        cmdClear.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cmdClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/filenew.png"))); // NOI18N
        cmdClear.setToolTipText("Clear Frame");
        cmdClear.setBorderPainted(false);
        cmdClear.setFocusable(false);
        cmdClear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdClear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearEntryField(evt);
            }
        });
        jToolBar1.add(cmdClear);

        cmdSave.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cmdSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/save.png"))); // NOI18N
        cmdSave.setToolTipText("SAVE/UPDATE");
        cmdSave.setBorderPainted(false);
        cmdSave.setFocusable(false);
        cmdSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveUserRights(evt);
            }
        });
        jToolBar1.add(cmdSave);
        jToolBar1.add(jSeparator1);
        jToolBar1.add(jSeparator2);

        cmdClose.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cmdClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/close.png"))); // NOI18N
        cmdClose.setToolTipText("CLOSE");
        cmdClose.setBorderPainted(false);
        cmdClose.setFocusable(false);
        cmdClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseFrame(evt);
            }
        });
        jToolBar1.add(cmdClose);

        FileMenu.setText("RECORD");
        FileMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        SaveItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        SaveItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        SaveItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/save.png"))); // NOI18N
        SaveItem.setText("SAVE");
        SaveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveUserRights(evt);
            }
        });
        FileMenu.add(SaveItem);

        MenuBar.add(FileMenu);

        FormMenu.setText("FORM");
        FormMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        CloseItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CloseItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        CloseItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/close.png"))); // NOI18N
        CloseItem.setText("CLOSE");
        CloseItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseFrame(evt);
            }
        });
        FormMenu.add(CloseItem);

        MenuBar.add(FormMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveUserRights(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveUserRights
        // TODO add your handling code here:
        if (pwdPassword.getPassword().length == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Password is required.", title, javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.Statement psmt = jdbc.createStatement()) {

            StringBuilder permits = new StringBuilder();
            short length = (short)checkBoxes.size();
            for (short abc = 0; abc <= length; abc++) {
                if (abc == length) {
                    length = (short)permits.length();
                    permits.deleteCharAt(length - 1);
                    break;
                }
                
                boolean test = checkBoxes.get(abc).isSelected();
                permits.append(test ? "true" : "false").append("~");
            }
            
            
            dbase.SQLExecute saver = new dbase.SQLExecute("public.userlogon");
            saver.FieldName("userid",     !NUMERIC, enums.Take.InsertOnly, CONDITION, txtUserID.getText());
            saver.FieldName("passwrd",    !NUMERIC, enums.Take.InsertUpdate, ".");
            saver.FieldName("userdescrp", !NUMERIC, enums.Take.InsertUpdate, txtUserName.getText());
            saver.FieldName("phaseoff",    NUMERIC, enums.Take.InsertUpdate, "FALSE");
            saver.FieldName("permeso",    !NUMERIC, enums.Take.InsertUpdate, permits);
            saver.FieldName("which",      !NUMERIC, enums.Take.InsertUpdate, "cmo");
            saver.FieldName("pazzword",    NUMERIC, enums.Take.InsertUpdate, "crypt('" + String.valueOf(pwdPassword.getPassword()) + "', gen_salt('bf'))");
            int success = psmt.executeUpdate(saver.Perform(enums.Fire.doUpdate));
            if (success == 0)
                success = psmt.executeUpdate(saver.Perform(enums.Fire.doInsert));

            if (success > 0)
                javax.swing.JOptionPane.showMessageDialog(this, "Record saved successfully.", title, javax.swing.JOptionPane.INFORMATION_MESSAGE);
            else
                javax.swing.JOptionPane.showMessageDialog(this, "Record failed to saved.", title, javax.swing.JOptionPane.INFORMATION_MESSAGE);
            pwdPassword.setText("");
            ReloadUser();


        } catch (java.sql.SQLException | java.awt.HeadlessException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(CreateUserJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_SaveUserRights

    private void CloseFrame(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseFrame
        // TODO add your handling code here:
        doDefaultCloseAction();
    }//GEN-LAST:event_CloseFrame

    private void InternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_InternalFrameOpened
        // TODO add your handling code here:
        checkBoxes.add(CheckBox1);
        checkBoxes.add(CheckBox2);
        checkBoxes.add(CheckBox3);
        checkBoxes.add(CheckBox4);
        checkBoxes.add(CheckBox5);
        
        ReloadUser();
    }//GEN-LAST:event_InternalFrameOpened

    private void ClearEntryField(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearEntryField
        // TODO add your handling code here:
        pwdPassword.setText("");
        cboUserID.setSelectedItem(null);
    }//GEN-LAST:event_ClearEntryField

    private void cboUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUserIDActionPerformed
        // TODO add your handling code here:
        int index = cboUserID.getSelectedIndex();
        if (index < 0) return;
        
        txtUserID.setText(LogList.get(index).getUserID());
        txtUserName.setText(cboUserID.getSelectedItem().toString());
        
        short test = (short)LogList.get(index).getPermiso().length;
        if (test > 0) {
            String[] PERMESO = LogList.get(index).getPermiso();
            for (short abc = 0; abc < test; abc ++) {
                boolean value = Boolean.parseBoolean(PERMESO[abc]);
                checkBoxes.get(abc).setSelected(value);
            }
        } else {
            CheckBox1.setSelected(false);
            CheckBox2.setSelected(false);
            CheckBox3.setSelected(false);
            CheckBox4.setSelected(false);
            CheckBox5.setSelected(false);
        }
    }//GEN-LAST:event_cboUserIDActionPerformed

    private void ReloadUser() {
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.PreparedStatement psmt = jdbc.prepareStatement(
                    "SELECT " +
                        "userid, " +
                        "userdescrp, " +
                        "permeso " +
                    "FROM " +
                        "public.userlogon " +
                    "WHERE " +
                        "(phaseoff = false) AND " +
                        "(pazzword IS NOT NULL) " +
                    "ORDER BY " +
                        "userid");
                java.sql.ResultSet rst = psmt.executeQuery()) {
            LogList.clear();
            cboUserID.removeAllItems();
            while (rst.next()) {
                boolean test = rst.getString(3) != null;
                test = test ? rst.getString(3).contains("~"): test;
                String[] PERMESO = (test ? rst.getString(3).split("~") : new String[]{});

                UserLogon users = new UserLogon(rst.getString(1), PERMESO);
                LogList.add(users);
                cboUserID.addItem(rst.getString(2));
            }

            
        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(CreateUserJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox1;
    private javax.swing.JCheckBox CheckBox2;
    private javax.swing.JCheckBox CheckBox3;
    private javax.swing.JCheckBox CheckBox4;
    private javax.swing.JCheckBox CheckBox5;
    private javax.swing.JComboBox<String> cboUserID;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
    private final boolean NUMERIC   = true,
                          CONDITION = true;
    
    private class UserLogon {
        
        private final String userID;
        private final String[] Permeso;

        public UserLogon(String userid, String[] permit) {
            userID = userid; Permeso = permit;
        }

        public String getUserID() {return userID;}
        public String[] getPermiso() {return Permeso;}
        
    }
}
