/*
 * UserIFrm.java
 *
 * Created on December 16, 2008, 1:57 PM
 */

package gov.admin;

/**
 *
 * @author  felixiong
 */
public class EraseUserJFrame extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 7130032058172741474L;

    private final java.util.ArrayList<String> LogList = new java.util.ArrayList<>();

    /** Creates new form UserIFrm */
    @SuppressWarnings("this-escape")
    public EraseUserJFrame() {initComponents();}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JTabbedPane jTabbedPane1 = new javax.swing.JTabbedPane();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        cboUserID = new javax.swing.JComboBox<>();
        txtUserID = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JToolBar jToolBar1 = new javax.swing.JToolBar();
        javax.swing.JButton cmdSave = new javax.swing.JButton();
        javax.swing.JToolBar.Separator jSeparator1 = new javax.swing.JToolBar.Separator();
        javax.swing.JToolBar.Separator jSeparator2 = new javax.swing.JToolBar.Separator();
        javax.swing.JButton cmdClose = new javax.swing.JButton();
        javax.swing.JMenuBar MenuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu RecordMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem EraseItem = new javax.swing.JMenuItem();
        javax.swing.JMenu FormMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem CloseItem = new javax.swing.JMenuItem();

        setClosable(true);
        setTitle("DELETE USER ACCOUNT");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/leaf.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                InternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("USER NAME");

        cboUserID.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cboUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIDActionPerformed(evt);
            }
        });

        txtUserID.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("USER I.D.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserID)
                    .addComponent(cboUserID, 0, 259, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("USER", jPanel1);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        cmdSave.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cmdSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/delete.png"))); // NOI18N
        cmdSave.setToolTipText("ERASE");
        cmdSave.setBorderPainted(false);
        cmdSave.setFocusable(false);
        cmdSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdSave.setOpaque(false);
        cmdSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EraseUser(evt);
            }
        });
        jToolBar1.add(cmdSave);
        jToolBar1.add(jSeparator1);
        jToolBar1.add(jSeparator2);

        cmdClose.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cmdClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/close.png"))); // NOI18N
        cmdClose.setToolTipText("CLOSE");
        cmdClose.setBorderPainted(false);
        cmdClose.setFocusable(false);
        cmdClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseFrame(evt);
            }
        });
        jToolBar1.add(cmdClose);

        RecordMenu.setText("RECORD");
        RecordMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        EraseItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        EraseItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        EraseItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/delete.png"))); // NOI18N
        EraseItem.setText("ERASE");
        EraseItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EraseUser(evt);
            }
        });
        RecordMenu.add(EraseItem);

        MenuBar.add(RecordMenu);

        FormMenu.setText("FORM");
        FormMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        CloseItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CloseItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        CloseItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/close.png"))); // NOI18N
        CloseItem.setText("CLOSE");
        CloseItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseFrame(evt);
            }
        });
        FormMenu.add(CloseItem);

        MenuBar.add(FormMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EraseUser(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EraseUser
        // TODO add your handling code here:
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.PreparedStatement psmt = jdbc.prepareStatement("DELETE FROM public.userlogon WHERE (userid = ?)")) {
            
            Object[] options = {"Yes", "No"};

            boolean test = javax.swing.JOptionPane.showOptionDialog(
                    this,
                    "Are you sure to delete this item?", title,
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[options.length - 1]) == javax.swing.JOptionPane.NO_OPTION;
            if (test) return;
        
            int index = cboUserID.getSelectedIndex();
            String userid = LogList.get(index);
            psmt.setString(1, userid);
            psmt.executeUpdate();
            
            
        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(EraseUserJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EraseUser

    private void CloseFrame(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseFrame
        // TODO add your handling code here:
        doDefaultCloseAction();
    }//GEN-LAST:event_CloseFrame

    private void InternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_InternalFrameOpened
        // TODO add your handling code here:
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.PreparedStatement psmt = jdbc.prepareStatement("SELECT userid, userdescrp FROM public.userlogon WHERE (pazzword IS NOT NULL) ORDER BY userdescrp");
                java.sql.ResultSet rst = psmt.executeQuery()) {
            LogList.clear(); cboUserID.removeAllItems();
            while (rst.next()) {
                LogList.add(rst.getString(1));
                cboUserID.addItem(rst.getString(2));
            }
            
            
        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(EraseUserJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_InternalFrameOpened

    private void userIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIDActionPerformed
        // TODO add your handling code here:
        int index = cboUserID.getSelectedIndex();
        if (index < 0) return;
        
        txtUserID.setText(LogList.get(index));
    }//GEN-LAST:event_userIDActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboUserID;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
    
}
