package gov.find;

/**
 *
 * @author felix
 */
public class ConsolidateFrame extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = -2589589417544082665L;
    
    private final transient java.util.Map<String, Boolean> mapa = new java.util.HashMap<>();
    private final transient java.util.List<String> arFunds = new java.util.ArrayList<>();

    /**
     * Creates new form LocateFrame
     */
    public ConsolidateFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        payrollItem = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator1 = new javax.swing.JPopupMenu.Separator();
        alobsItem = new javax.swing.JMenuItem();
        menuPopup = new javax.swing.JPopupMenu();
        clearItems = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator2 = new javax.swing.JPopupMenu.Separator();
        removeItem = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator3 = new javax.swing.JPopupMenu.Separator();
        retrieveItem = new javax.swing.JMenuItem();
        BatchCtrl = new java.lang.String();
        txtCtrlNo = new javax.swing.JTextField();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        btnAppend = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        spnYear = new javax.swing.JSpinner();
        tabbedPane = new javax.swing.JTabbedPane();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        tblWages = new javax.swing.JTable();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        txt2ndName = new javax.swing.JTextField();
        txt2ndRank = new javax.swing.JTextField();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        txt1stName = new javax.swing.JTextField();
        txt1stRank = new javax.swing.JTextField();
        javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
        txt3rdName = new javax.swing.JTextField();
        txt3rdRank = new javax.swing.JTextField();
        btnAlter = new javax.swing.JButton();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
        txtDetail = new javax.swing.JTextArea();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        txtPayee = new javax.swing.JTextField();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        fmtAlobsNo = new javax.swing.JFormattedTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        cboFunds = new javax.swing.JComboBox<>();
        txtOffice = new javax.swing.JTextField();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        txtDeptHead = new javax.swing.JTextField();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        txtRanggo = new javax.swing.JTextField();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        dtpDated = new com.toedter.calendar.JDateChooser();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        txtBudgetary = new javax.swing.JTextField();
        javax.swing.JLabel jLabel14 = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        fmtTotal = new javax.swing.JFormattedTextField();
        btnMenu = new javax.swing.JButton();
        cboSelect = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();

        payrollItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        payrollItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/salary.png"))); // NOI18N
        payrollItem.setText("Payroll View/Print");
        payrollItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payrollItemActionPerformed(evt);
            }
        });
        popupMenu.add(payrollItem);
        popupMenu.add(jSeparator1);

        alobsItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        alobsItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/memo.png"))); // NOI18N
        alobsItem.setText("ALOBS View/Print");
        alobsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alobsItemActionPerformed(evt);
            }
        });
        popupMenu.add(alobsItem);

        clearItems.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        clearItems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/filenew.png"))); // NOI18N
        clearItems.setText("Clear Entry Form");
        clearItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearItemsActionPerformed(evt);
            }
        });
        menuPopup.add(clearItems);
        menuPopup.add(jSeparator2);

        removeItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        removeItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/remove.png"))); // NOI18N
        removeItem.setText("Remove Row");
        removeItem.setEnabled(false);
        removeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeItemActionPerformed(evt);
            }
        });
        menuPopup.add(removeItem);
        menuPopup.add(jSeparator3);

        retrieveItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        retrieveItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/retrieve.png"))); // NOI18N
        retrieveItem.setText("Retrieve Batch Payroll");
        retrieveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrieveItemActionPerformed(evt);
            }
        });
        menuPopup.add(retrieveItem);

        setClosable(true);
        setTitle("Payroll Consolidation");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Control #");

        btnAppend.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnAppend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/pluz.png"))); // NOI18N
        btnAppend.setBorderPainted(false);
        btnAppend.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAppend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wagesActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/printer.png"))); // NOI18N
        btnView.setText("Preview");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Year:");

        spnYear.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        spnYear.setModel(new javax.swing.SpinnerNumberModel(2000, 2000, 3000, 1));
        spnYear.setEditor(new javax.swing.JSpinner.NumberEditor(spnYear, "#0"));

        tabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPaneStateChanged(evt);
            }
        });

        tblWages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ctrl No.", "Name", "Period", "Office", "Charges", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblWages.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblWages);
        if (tblWages.getColumnModel().getColumnCount() > 0) {
            tblWages.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblWages.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblWages.getColumnModel().getColumn(2).setPreferredWidth(160);
            tblWages.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblWages.getColumnModel().getColumn(4).setPreferredWidth(200);
            tblWages.getColumnModel().getColumn(5).setPreferredWidth(120);
            tblWages.getColumnModel().getColumn(5).setCellRenderer(new tables.DecimalFormatColumnRender(tables.DecimalFormatColumnRender.COMMA_SEPARATED, (short)2, tables.DecimalFormatColumnRender.RIGHT));
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "2nd Signatory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        txt2ndName.setText("Atty. CRISTINA R. PARIÑAS");

        txt2ndRank.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt2ndRank.setText("City Administrator");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt2ndName, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(txt2ndRank))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt2ndName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt2ndRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "1st Signatory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        txt1stName.setText("HAIREE CEL S. PEDIMONTE");

        txt1stRank.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt1stRank.setText("CGDH-I CHRMD Officer");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt1stName, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(txt1stRank))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt1stName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt1stRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "3rd Signatory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        txt3rdName.setText("Atty. CRISTINA R. PARIÑAS");

        txt3rdRank.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt3rdRank.setText("City Administrator");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt3rdName, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(txt3rdRank))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt3rdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt3rdRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAlter.setText("Update Signatory");
        btnAlter.setBorderPainted(false);
        btnAlter.setFocusable(false);
        btnAlter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlter, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAlter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        tabbedPane.addTab("Payroll / Wage", jPanel2);

        txtDetail.setColumns(20);
        txtDetail.setRows(5);
        jScrollPane3.setViewportView(txtDetail);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("PAYEE");

        txtPayee.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Details");

        btnUpdate.setText("Prepare ALOBS");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        fmtAlobsNo.setEditable(false);
        try {
            fmtAlobsNo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fmtAlobsNo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("ALOBS #:");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("Funds");

        cboFunds.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        txtOffice.setEditable(false);
        txtOffice.setText("EXECUTIVE SERVICES (CMO)");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setText("OFFICE");

        txtDeptHead.setText("PABLO YVES L. DUMLAO II");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setText("DEP'T HEAD");

        txtRanggo.setText("City Mayor");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setText("Designation");

        dtpDated.setDate(new java.util.Date());
        dtpDated.setDateFormatString("MM/dd/yyyy");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel12.setText("DATE");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setText("BUDGET OFFCR.");

        txtBudgetary.setText("ATTY. JEFFREY P. GALIDO, CPA");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel14.setText("Designation");

        txtPosition.setText("City Budget Officer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPayee, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fmtAlobsNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeptHead, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRanggo, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtpDated, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cboFunds, 0, 282, Short.MAX_VALUE)
                                            .addComponent(txtBudgetary)
                                            .addComponent(txtPosition))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdate)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fmtAlobsNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(cboFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPayee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtBudgetary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeptHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRanggo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtpDated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUpdate)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("ALOBS", jPanel1);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("T O T A L");

        fmtTotal.setEditable(false);
        fmtTotal.setForeground(new java.awt.Color(255, 0, 0));
        fmtTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        fmtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fmtTotal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        fmtTotal.setValue(0D);

        btnMenu.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        cboSelect.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cboSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Job Order", "Contractual" }));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Selection");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbedPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCtrlNo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAppend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fmtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnView)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnView)
                        .addComponent(jLabel2)
                        .addComponent(spnYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(fmtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMenu)
                        .addComponent(cboSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCtrlNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7))
                    .addComponent(btnAppend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane)
                .addContainerGap())
        );

        getRootPane().setDefaultButton(btnAppend);

        setBounds(0, 0, 1033, 711);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        if (evt == null) return;
        
        tblWages.getSelectionModel().addListSelectionListener((javax.swing.event.ListSelectionEvent lse) -> {
            if (lse.getValueIsAdjusting()) return; //System.out.println("valueChanged");

            removeItem.setEnabled(tblWages.getSelectedRowCount() > 0);
        });
        tblWages.getModel().addTableModelListener((javax.swing.event.TableModelEvent tme) -> {
            if (tme.getType() == javax.swing.event.TableModelEvent.UPDATE) return;
            
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblWages.getModel();
            long amount = 0L;
            for (short abc = 0; abc < modelo.getRowCount(); abc++) {
                if (modelo.getValueAt(abc, 5) != null) amount += Math.round(((Double)modelo.getValueAt(abc, 5)) * 100D);
            }
            fmtTotal.setValue(amount * 0.01D);
        });
        
        
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                org.postgresql.core.BaseConnection jdvc = new gov.hrisjo.PGdbLink("financial")) {
            
            try (java.sql.Statement _smt = jdbc.createStatement();
                    java.sql.ResultSet rst = _smt.executeQuery("SELECT DATE_PART('YEAR', NOW());")) {
                if (rst.next()) spnYear.setValue(rst.getInt(1));
            }
            try (java.sql.PreparedStatement psmt = jdvc.prepareStatement("SELECT coding, describe FROM obro.mgafunds ORDER BY funded;");
                    java.sql.ResultSet rst = psmt.executeQuery()) {
                while (rst.next()) {
                    arFunds.add(rst.getString(1));
                    cboFunds.addItem(rst.getString(2));
                }
            }
            dtpDated.setDate(gov.hrisjo.MainJFrame.getPetsaRon());
            
        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(ConsolidateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void wagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wagesActionPerformed
        // TODO add your handling code here:
        Integer ctrlno, idx = cboSelect.getSelectedIndex();
        String text = txtCtrlNo.getText();
        if (!text.trim().isBlank() || !text.isBlank())
            ctrlno = Integer.valueOf(text, 10);
        else {
            btnAppend.setToolTipText(evt.getActionCommand());
            return;
        }

        text = spnYear.getValue() + "~" + new java.text.DecimalFormat("000000").format(ctrlno);
        if (idx == 0)
            JobOrder(text);
        else
            Contractual(text);
    }//GEN-LAST:event_wagesActionPerformed

    private void JobOrder(String text) {
        String already, pangalan, periodas, opesina, proyekto, inputby;
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink()) {

            Double cantedad; //, amount = Double.valueOf(fmtTotal.getValue().toString());
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblWages.getModel();
            inputby = "SELECT " +
                            "MIN(humane(jobworker.lastname, jobworker.firstname, jobworker.suffix, jobworker.midname)), " +
                            "TO_CHAR(MIN(timebook.datefr), 'MM/DD/YYYY') || ' - ' || TO_CHAR(MAX(timebook.dateto), 'MM/DD/YYYY'), " +
                            "offices.office, " +
                            "projects.projtitle, " +
                            "SUM((timebook.days * timebook.rate) - (((timebook.rate / 480.0) * timebook.utime)::numeric(18, 2)) + timebook.bunos), " + // - timebook.pag_ibig - timebook.sssprem), " +
                            "timebook.alobs, " +
                            "projects.projid, " +
                            "offices.offcid, " +
                            "COUNT(*) " +
                        "FROM " +
                            "psnl.jobworker INNER JOIN pay.timebook " +
                            "ON jobworker.uniqkey = timebook.worker " +
                            "INNER JOIN cbo.projects ON timebook.proyekto = projects.projid " +
                            "INNER JOIN psnl.offices " +
                            "ON timebook.opesina = offices.offcid " +
                        "WHERE " +
                            "(timebook.ctrlno = '" + text + "') " +
                            //"(timebook.alobs IS NULL) " +
                        "GROUP BY " +
                            "offices.office, " +
                            "timebook.alobs, " +
                            "projects.projtitle, " +
                            "projects.projid, " +
                            "offices.offcid";

            try (java.sql.Statement _smt = jdbc.createStatement();
                    java.sql.ResultSet rst = _smt.executeQuery(inputby)) {
                if (rst.next()) {
                    if (rst.getString(6) == null) {
                        Object[] rowData = {
                            text,
                            rst.getString(1).toUpperCase() + (rst.getShort(9) > 1 ? " ET AL," : ""),
                            rst.getString(2),
                            rst.getString(3),
                            rst.getString(4),
                            rst.getDouble(5)
                        };
                        pangalan = rst.getString(1).toUpperCase() + (rst.getShort(9) > 1 ? " ET AL," : "");
                        periodas = rst.getString(2);
                        cantedad = rst.getDouble(5);
                        proyekto = rst.getString(7);
                        opesina  = rst.getString(8);
                        inputby  = System.getProperty("USERID");
                        
                        if (!mapa.containsKey(text)) modelo.addRow(rowData);
//                            amount += rst.getDouble(5);
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Ctrl No: " + text + " has an ALOBS Number already.", getTitle(), javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Control Number not exist!", getTitle(), javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
//            fmtTotal.setValue(amount);
            txtCtrlNo.setText("");
            
            boolean test = BatchCtrl.isBlank(); test |= BatchCtrl.isEmpty(); test |= BatchCtrl.isBlank();
            if (test) try (java.sql.Statement _smt = jdbc.createStatement();
                    java.sql.ResultSet rst = _smt.executeQuery("SELECT * FROM pay.nextconsol(" + spnYear.getValue() + "::INTEGER);")) {
                if (rst.next() & BatchCtrl.isEmpty()) {
                    BatchCtrl = spnYear.getValue() + "~" + new java.text.DecimalFormat("000000").format(rst.getInt(1));
                    setTitle(TITLE + " <" + BatchCtrl + ">");
                }
            }
            if (!mapa.containsKey(text)) {
                already = "INSERT INTO pay.consolwages(consolid, pangalan, periodas, opesina, proyekto, cantedad, inputby, wagectrlno, name1st, rank1st, name2nd, rank2nd, name3rd, rank3rd) " + 
                          "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
                try (java.sql.PreparedStatement psmt = jdbc.prepareStatement(already)) {
                    psmt.setString(1, BatchCtrl);
                    psmt.setString(2, pangalan);
                    psmt.setString(3, periodas);
                    psmt.setString(4, opesina);
                    psmt.setString(5, proyekto);
                    psmt.setDouble(6, cantedad);
                    psmt.setString(7, inputby);
                    psmt.setString(8, text);
                    /*---------------------------------------------------------*/
                    psmt.setString(9, txt1stName.getText());
                    psmt.setString(10, txt1stRank.getText());
                    psmt.setString(11, txt2ndName.getText());
                    psmt.setString(12, txt2ndRank.getText());
                    psmt.setString(13, txt3rdName.getText());
                    psmt.setString(14, txt3rdRank.getText());
                    psmt.executeUpdate();
                }
//                try (java.sql.PreparedStatement psmt = jdbc.prepareStatement("UPDATE pay.timebook SET alobs = ? WHERE ctrlno = ?;")) {
//                    psmt.setString(1, alobs_id);
//                    psmt.setString(2, text);
//                    psmt.executeUpdate();
//                }
                
                mapa.put(text, true);
                cboSelect.setEnabled(false);
            }



        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(ConsolidateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }
    private void Contractual(String text) {
        String already, pangalan, periodas, opesina, proyekto, inputby;
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink()) {

            Double cantedad; //, amount = Double.valueOf(fmtTotal.getValue().toString());
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblWages.getModel();
            inputby = "SELECT " +
                            "MIN(humane(jobworker.lastname, jobworker.firstname, jobworker.suffix, jobworker.midname)), " +
                            "TO_CHAR(MIN(laborpaid.datefr), 'MM/DD/YYYY') || ' - ' || TO_CHAR(MAX(laborpaid.dateto), 'MM/DD/YYYY'), " +
                            "offices.office, " +
                            "SUM(CASE WHEN ((laborpaid.frday < 16 AND laborpaid.today < 16) OR (laborpaid.frday = 16 AND laborpaid.today > 16)) THEN laborpaid.rate / 2.0 ELSE laborpaid.rate END - ((laborpaid.rate / 10560.0) * ((laborpaid.udays * 480.0) + laborpaid.utime))::numeric(18, 2) + laborpaid.bunos), " + // - laborpaid.pag_ibig - laborpaid.sssprem - laborpaid.withtax), " +
                            "laborpaid.alobs, " +
                            "offices.offcid, " +
                            "COUNT(*), " +
                            "jobworker.bank_acct IS NULL " +
                        "FROM " +
                            "psnl.jobworker INNER JOIN pay.laborpaid " +
                            "ON jobworker.uniqkey = laborpaid.worker " +
                            "INNER JOIN psnl.offices " +
                            "ON laborpaid.opesina = offices.offcid " +
                        "WHERE " +
                            "(laborpaid.ctrlno = '" + text + "') " +
                            //"(" + WAGES[idx] + ".alobs IS NULL) " +
                        "GROUP BY " +
                            "offices.office, " +
                            "laborpaid.alobs, " +
                            "jobworker.bank_acct IS NULL, " +
                            "offices.offcid;";

            try (java.sql.Statement _smt = jdbc.createStatement();
                    java.sql.ResultSet rst = _smt.executeQuery(inputby)) {
                if (rst.next()) {
                    if (NotATM == null) NotATM = rst.getBoolean(8);
                    if (NotATM != rst.getBoolean(8)) {
                        javax.swing.JOptionPane.showMessageDialog(this, "You ENTERED a Payroll on " + (NotATM ? "C/A" : "ATM") + " Mode.", title, javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    
                    if (rst.getString(5) == null) {
                        Object[] rowData = {
                            text,
                            rst.getString(1).toUpperCase() + (rst.getShort(7) > 1 ? " ET AL," : ""),
                            rst.getString(2),
                            rst.getString(3),
                            "",
                            rst.getDouble(4)
                        };
                        pangalan = rst.getString(1).toUpperCase() + (rst.getShort(7) > 1 ? " ET AL," : "");
                        periodas = rst.getString(2);
                        cantedad = rst.getDouble(4);
                        proyekto = "";
                        opesina  = rst.getString(6);
                        inputby  = System.getProperty("USERID");
                        
                        
                        if (!mapa.containsKey(text)) modelo.addRow(rowData);
//                            amount += rst.getDouble(4);
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Ctrl No: " + text + " has an ALOBS Number already.", title, javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Control Number not exist!", title, javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
//            fmtTotal.setValue(amount);
            txtCtrlNo.setText("");
            
            boolean test = BatchCtrl == null;
            if (!test) {
                test |= BatchCtrl.isEmpty();
                test |= BatchCtrl.isBlank();
            }
            if (test) try (java.sql.Statement _smt = jdbc.createStatement();
                    java.sql.ResultSet rst = _smt.executeQuery("SELECT * FROM pay.nextconsol(" + spnYear.getValue() + "::INTEGER);")) {
                if (rst.next() & BatchCtrl.isEmpty()) {
                    BatchCtrl = spnYear.getValue() + "~" + new java.text.DecimalFormat("000000").format(rst.getInt(1));
                    setTitle(TITLE + " <" + BatchCtrl + ">");
                }
            }
            if (!mapa.containsKey(text)) {
                already = "INSERT INTO pay.consolwages(consolid, pangalan, periodas, opesina, proyekto, cantedad, inputby, wagectrlno, name1st, rank1st, name2nd, rank2nd, name3rd, rank3rd) " +
                          "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
                try (java.sql.PreparedStatement psmt = jdbc.prepareStatement(already)) {
                    psmt.setString(1, BatchCtrl);
                    psmt.setString(2, pangalan);
                    psmt.setString(3, periodas);
                    psmt.setString(4, opesina);
                    psmt.setString(5, proyekto);
                    psmt.setDouble(6, cantedad);
                    psmt.setString(7, inputby);
                    psmt.setString(8, text);
                    /*---------------------------------------------------------*/
                    psmt.setString(9, txt1stName.getText());
                    psmt.setString(10, txt1stRank.getText());
                    psmt.setString(11, txt2ndName.getText());
                    psmt.setString(12, txt2ndRank.getText());
                    psmt.setString(13, txt3rdName.getText());
                    psmt.setString(14, txt3rdRank.getText());
                    psmt.executeUpdate();
                }
//                try (java.sql.PreparedStatement psmt = jdbc.prepareStatement("UPDATE pay.laborpaid SET alobs = ? WHERE ctrlno = ?;")) {
//                    psmt.setString(1, alobs_id);
//                    psmt.setString(2, text);
//                    psmt.executeUpdate();
//                }
                
                mapa.put(text, true);
                cboSelect.setEnabled(false);
            }



        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(ConsolidateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }
    
    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        popupMenu.show(btnView, 0, btnView.getHeight());
        
        boolean test = BatchCtrl.isBlank(); test |= BatchCtrl.isEmpty();
        payrollItem.setEnabled(!test);
    }//GEN-LAST:event_viewActionPerformed

    private void tabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedPaneStateChanged
        // TODO add your handling code here:
        int test = evt.hashCode();
        tabbedPane.setToolTipText(String.valueOf(test));
        test = tabbedPane.getSelectedIndex();
        switch (test) {
            case 1:
                String  sqlCmd =
                        "SELECT " +
                            "payee, " +         // 1
                            "particulars, " +   // 2
                            "obligated, " +     // 3
                      /* 4*/"depthead, " +
                      /* 5*/"posisyon, " +
                      /* 6*/"deptdate, " +
                      /* 7*/"budgetary, " +
                      /* 8*/"designate " +
                        "FROM " +
                            "obro.requests " +
                        "WHERE " +
                            "(alobs_id = ?)";
                
                try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink("financial");
                        java.sql.PreparedStatement psmt = jdbc.prepareStatement(sqlCmd)) {
                    
                    sqlCmd = fmtAlobsNo.getText();
                    psmt.setString(1, sqlCmd);
                    try (java.sql.ResultSet rst = psmt.executeQuery()) {
                        if (rst.next()) {
//                            boolean trials = rst.getBoolean(3);

//                            btnUpdate.setEnabled(true);
                            
//                            txtPayee.setEditable(trials);
                            txtDetail.setEditable(true);
                            
                            txtPayee    .setText(rst.getString(1));
                            txtDetail   .setText(rst.getString(2));
                            txtDeptHead .setText(rst.getString(4));
                            txtRanggo   .setText(rst.getString(5));
                            dtpDated    .setDate(rst.getDate(6));
                            txtBudgetary.setText(rst.getString(7));
                            txtPosition .setText(rst.getString(8));
                        } else {
//                            btnUpdate.setEnabled(false);
                            
                            txtPayee.setEditable(false);
                            txtDetail.setEditable(false);
                            
                            txtPayee.setText("");
                            txtDetail.setText("");
                        }
                    }
                    
                } catch (Exception fex) {
                    javax.swing.JOptionPane.showMessageDialog(this, fex.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
                    java.util.logging.Logger.getLogger(ConsolidateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, fex);
                } finally {
                    
                }
                break;
            
            default:
                System.out.println("nothing");
        }
    }//GEN-LAST:event_tabbedPaneStateChanged

    private void payrollItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payrollItemActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        
        int idx = cboSelect.getSelectedIndex();
        String[] reports = {"jobconsol", "contsolida"};
        java.io.InputStream reportSource = getClass().getResourceAsStream("/jreport/" + reports[idx] + ".jasper");
        try (java.sql.Connection jdbc = new gov.hrisjo.PGdbLink()) {
            
            // REPORT PARAMETERS
            java.util.Map<String, Object> params = new java.util.HashMap<>();
            params.put("CtrlNo", BatchCtrl);

            net.sf.jasperreports.engine.JasperPrint jasperPrint = net.sf.jasperreports.engine.JasperFillManager.fillReport(reportSource, params, jdbc);
            net.sf.jasperreports.view.JasperViewer.viewReport(jasperPrint, false);



        } catch (java.sql.SQLException | net.sf.jasperreports.engine.JRException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(ConsolidateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_payrollItemActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        String  insert =
                    "INSERT INTO " +
                        "obro.requests (" +
                            /* 1*/"years, " +
                            /* 2*/"alobs_id, " +
                            /* 3*/"payee, " +
                            /* 4*/"offc_code, " +
                            /* 5*/"office, " +
                            /* 6*/"particulars, " +
                            /* 7*/"amount, " +
                            /* 8*/"depthead, " +
                            /* 9*/"posisyon, " +
                            /*10*/"deptdate, " +
                            /*11*/"budgetary, " +
                            /*12*/"designate, " +
                            /*13*/"chargeto, " +
                            /*14*/"encoded, " +
                            /*15*/"seq_ord, " +
                                  "jo_pay) " +
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, true)",
                           //1  2  3  4  5  6  7  8  9  10 11 12 13 14 15
                update = 
                    "UPDATE " +
                        "obro.requests " +
                    "SET " +
                        "years       = ?, " +   // 1
                        "payee       = ?, " +   // 2
                        "offc_code   = ?, " +   // 3
                        "office      = ?, " +   // 4
                        "particulars = ?, " +   // 5
                        "amount      = ?, " +   // 6
                        "depthead    = ?, " +   // 7
                        "posisyon    = ?, " +   // 8
                        "deptdate    = ?, " +   // 9
                        "budgetary   = ?, " +   //10
                        "designate   = ?, " +   //11
                        "chargeto    = ?, " +   //12
                        "encoded     = ?  " +   //13
                    "WHERE " +
                        "(alobs_id = ?)";       //14
                //queries = "SELECT MIN(pangalan), proyekto, SUM(cantedad) FROM pay.consolwages WHERE (consolid = ?) GROUP BY proyekto ORDER BY MIN(pangalan);";
                //queries = "SELECT pangalan, cantedad FROM pay.consolwages WHERE (consolid = ?) ORDER BY pangalan;";
        try (java.sql.Connection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.Connection jdvc = new gov.hrisjo.PGdbLink("financial")) {
            
            Long Amount = 0L;
            try (java.sql.Statement _smt = jdbc.createStatement();
                    java.sql.ResultSet rst = _smt.executeQuery("SELECT MIN(pangalan), SUM(cantedad) FROM pay.consolwages WHERE (consolid = '" + BatchCtrl + "');")) {
                if (rst.next()) {
                    txtPayee.setText(rst.getString(1) + " ET AL...");
                    Amount = Math.round(rst.getDouble(2) * 100D);
                    fmtTotal.setValue(Amount * 0.01D);
                }
            }
            try (java.sql.Statement _smt = jdbc.createStatement();
                    java.sql.ResultSet rst = _smt.executeQuery("SELECT pangalan, cantedad FROM pay.consolwages WHERE (consolid = '" + BatchCtrl + "') ORDER BY pangalan;")) {
                
                String queries = txtDetail.getText();
                if (queries.isBlank()) 
                    queries = "To payment for services rendered \n\n";
                else {
                    int instr = queries.indexOf("...") + 3;
                    queries = queries.substring(0, instr) + "\n";
                }
                if (rst.next()) {
                    queries += rst.getString(1)+ "\t\t" + new java.text.DecimalFormat("#,##0.00").format(Amount * 0.01D) + "\r\n"; // rst.getDouble(2)
                }
                txtDetail.setText(queries);
            }
            
            java.util.Calendar cals = java.util.Calendar.getInstance();
            cals.setTime(gov.hrisjo.MainJFrame.getPetsaRon());
            
            int idx = cboFunds.getSelectedIndex();
            Short SeqOrder = 0, Years = Short.valueOf(spnYear.getValue().toString(), 10);
            Long petsa = dtpDated.getDate().getTime();
            String alobsid = fmtAlobsNo.getText(), Acronym,
                   ALOBS = new java.text.DecimalFormat("00").format(cals.get(java.util.Calendar.MONTH) + 1),
                   Funding = arFunds.get(idx),
                   DeptHead = txtDeptHead.getText().toUpperCase(),
                   Position = txtRanggo.getText(),
                   Budgetary = txtBudgetary.getText().toUpperCase(),
                   Designate = txtPosition.getText();
            
            
            boolean trial = !alobsid.equals("    -  -  -   ");
            if (trial) ALOBS = alobsid;
            
            alobsid = txtPayee.getText().toUpperCase();
            if (trial) {
                fmtAlobsNo.commitEdit();
                try (java.sql.PreparedStatement psmtu = jdvc.prepareStatement(update)) {
                    update = txtDetail.getText();                    
                    psmtu.setShort ( 1, Years);
                    psmtu.setString( 2, alobsid);
                    psmtu.setString( 3, OFFICE_CODE);
                    psmtu.setString( 4, OFFICE_NAME);
                    psmtu.setString( 5, update);
                    psmtu.setDouble( 6, Amount * 0.01D);
                    psmtu.setString( 7, DeptHead);
                    psmtu.setString( 8, Position);
                    psmtu.setDate  ( 9, new java.sql.Date(petsa));
                    psmtu.setString(10, Budgetary);
                    psmtu.setString(11, Designate);
                    psmtu.setString(12, Funding);
                    psmtu.setString(13, System.getProperty("USERID"));
                    /***************************/
                    psmtu.setString(14, ALOBS);
                    psmtu.executeUpdate();
                }
            } else try (java.sql.PreparedStatement psmt = jdvc.prepareStatement("SELECT COALESCE(MAX(seq_ord) + 1, 1) FROM obro.requests WHERE (alobs_id LIKE ?);");
                    java.sql.PreparedStatement psmti = jdvc.prepareStatement(insert);) {
                ALOBS += "-";
                ALOBS += String.valueOf(Years).substring(2);
                ALOBS += "-";
                ALOBS += Funding;                
                psmt.setString(1, "%-" + ALOBS);
                try (java.sql.ResultSet rst = psmt.executeQuery()) {
                    if (rst.next()) {
                        SeqOrder = rst.getShort(1);
                        Acronym = new java.text.DecimalFormat("0000").format(SeqOrder);
                    } else
                        Acronym = "0000";
                }
                insert = txtDetail.getText();
                
                ALOBS = Acronym + "-" + ALOBS;
                psmti.setShort ( 1, Years);
                psmti.setString( 2, ALOBS);
                psmti.setString( 3, alobsid);
                psmti.setString( 4, OFFICE_CODE);
                psmti.setString( 5, OFFICE_NAME);
                psmti.setString( 6, insert);
                psmti.setDouble( 7, Amount * 0.01D);
                psmti.setString( 8, DeptHead);
                psmti.setString( 9, Position);
                psmti.setDate  (10, new java.sql.Date(petsa));
                psmti.setString(11, Budgetary);
                psmti.setString(12, Designate);
                psmti.setString(13, Funding);
                psmti.setString(14, System.getProperty("USERID"));
                psmti.setShort (15, SeqOrder);
                psmti.executeUpdate();
                
                fmtAlobsNo.setValue(ALOBS);
            }
            
            idx = cboSelect.getSelectedIndex();
            String[] reports = {"timebook", "laborpaid"};
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblWages.getModel();
            try (java.sql.PreparedStatement psmt = jdbc.prepareStatement("UPDATE pay." + reports[idx] + " SET alobs = ? WHERE ctrlno = ?;");
                    java.sql.PreparedStatement pzmt = jdbc.prepareStatement("UPDATE pay.consolwages SET alobs_id = ? WHERE (consolid = ?);")) {
                pzmt.setString(1, ALOBS);
                pzmt.setString(2, BatchCtrl);
                pzmt.executeUpdate();
                
                for(short abc = 0; abc < modelo.getRowCount(); abc++) {
                    String text = modelo.getValueAt(abc, 0).toString();
                    psmt.setString(1, ALOBS);
                    psmt.setString(2, text);
                    psmt.executeUpdate();
                }
            }
            alobsItemActionPerformed(evt);


        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(ConsolidateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_updateActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        retrieveItem.setEnabled(BatchCtrl.isBlank() | BatchCtrl.isEmpty()); 
        menuPopup.show(btnMenu, 0, btnMenu.getHeight());
    }//GEN-LAST:event_menuActionPerformed

    private void clearItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearItemsActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        BatchCtrl = "";
        fmtAlobsNo.setValue(null);
//        fmtTotal.setValue(0D);
        txtPayee.setText("");
        txtDetail.setText("");
        setTitle(TITLE);
        
        NotATM = null;
        
        
        cboSelect.setEnabled(true);
        
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblWages.getModel();
        modelo.setNumRows(0);
        
//        txt1stName.setText("");
//        txt1stRank.setText("");
//        txt2ndName.setText("");
//        txt2ndRank.setText("");
//        txt3rdName.setText("");
//        txt3rdRank.setText("");
    }//GEN-LAST:event_clearItemsActionPerformed

    private void retrieveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrieveItemActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        BatchCtrlDialog dialogo = new BatchCtrlDialog();
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
        
        String sqlCmd;
        BatchCtrl = dialogo.getBatchCtrl(); dialogo.dispose();
        if (BatchCtrl == null || (BatchCtrl.isBlank() | BatchCtrl.isEmpty())) return;
        
        sqlCmd = "SELECT " +
                    "consolwages.pangalan, " +
                    "consolwages.periodas, " +
                    "offices.office, " +
                    "projects.projtitle, " +
                    "consolwages.cantedad, " +
                    "consolwages.wagectrlno, " +
                    "consolwages.alobs_id, " +
                    "consolwages.name1st, " +
                    "consolwages.rank1st, " +
                    "consolwages.name2nd, " +
                    "consolwages.rank2nd, " +
                    "consolwages.name3rd, " +
                    "consolwages.rank3rd, " +
                    "suholan.typed = 'C/A' " +
                "FROM " +
                    "pay.consolwages INNER JOIN cbo.projects " +
                    "ON consolwages.proyekto = projects.projid " +
                    "INNER JOIN psnl.offices " +
                    "ON consolwages.opesina = offices.offcid " +
                    "INNER JOIN pay.suholan " +
                    "ON consolwages.wagectrlno = suholan.ctrlno " +
                "WHERE " +
                    "(consolwages.consolid = ?) " +
                "ORDER BY " +
                    "consolwages.wagectrlno;";
        try (java.sql.Connection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.PreparedStatement psmt = jdbc.prepareStatement(sqlCmd)) {
            
//            Double amount = 0D;
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblWages.getModel();
            modelo.setNumRows(0);
            
            String[] anios = BatchCtrl.split("~");
            Integer anyos = Integer.valueOf(anios[0], 10);
            spnYear.setValue(anyos);
            
            psmt.setString(1, BatchCtrl);
            try (java.sql.ResultSet rst = psmt.executeQuery()) {
                while (rst.next()) {
                    Object[] rowData = {
                        rst.getString(6),
                        rst.getString(1),
                        rst.getString(2),
                        rst.getString(3),
                        rst.getString(4),
                        rst.getDouble(5)
                    };
                    modelo.addRow(rowData);
                    mapa.put(rst.getString(6), true);
//                    amount += rst.getDouble(5);
                    fmtAlobsNo.setValue(rst.getString(7));

                    txt1stName.setText(rst.getString(8));
                    txt1stRank.setText(rst.getString(9));
                    txt2ndName.setText(rst.getString(10));
                    txt2ndRank.setText(rst.getString(11));
                    txt3rdName.setText(rst.getString(12));
                    txt3rdRank.setText(rst.getString(13));
                    
                    NotATM = rst.getBoolean(14);
                    
                    boolean test = rst.getString(4).isBlank(); test |= rst.getString(4).isEmpty();
                    cboSelect.setSelectedIndex(test ? 1 : 0);
                    
                    cboSelect.setEnabled(false);
                }
            }
            if (modelo.getRowCount() > 0) setTitle(TITLE + " <" + BatchCtrl + ">");
//            fmtTotal.setValue(amount);


        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(ConsolidateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_retrieveItemActionPerformed

    private void removeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeItemActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        int idx = cboSelect.getSelectedIndex();
        
        Object[] options = {"Yes", "No"};
        boolean test = javax.swing.JOptionPane.showOptionDialog(
                this,
                "Are you sure to remove this item?", title,
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[options.length - 1]) == javax.swing.JOptionPane.NO_OPTION;
        if (test) return;
        
        int selrow = tblWages.getSelectedRow();
        selrow = tblWages.convertRowIndexToModel(selrow);
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblWages.getModel();
        String wageCtrl = modelo.getValueAt(selrow, 0).toString();
        
        try (java.sql.Connection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.Connection jdvc = new gov.hrisjo.PGdbLink("financial")) {
            
            try(java.sql.PreparedStatement psmt = jdbc.prepareStatement("UPDATE pay." + WAGES[idx] + " SET alobs = NULL WHERE (ctrlno = ?);")) {
                psmt.setString(1, wageCtrl);
                psmt.executeUpdate();
            }
            try(java.sql.PreparedStatement psmt = jdbc.prepareStatement("DELETE FROM pay.consolwages WHERE (wagectrlno = ?);")) {
                psmt.setString(1, wageCtrl);
                psmt.executeUpdate();
            }
            modelo.removeRow(selrow);
            mapa.remove(wageCtrl);
            
            int best = modelo.getRowCount();
            if (best <= 0) {
                BatchCtrl = "";
                cboSelect.setEnabled(true);
//                fmtTotal.setValue(0);
                setTitle(TITLE);
                
                if (fmtAlobsNo.getValue() != null) {
                    String alobsid = fmtAlobsNo.getValue().toString();
                    try(java.sql.PreparedStatement psmt = jdvc.prepareStatement("DELETE FROM obro.requests WHERE (alobs_id = ?);")) {
                        psmt.setString(1, alobsid);
                        psmt.executeUpdate();
                    }
                }
            }
            

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(ConsolidateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_removeItemActionPerformed

    private void alterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().isBlank() | evt.getActionCommand().isEmpty()) return;
        
        try (java.sql.Connection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.PreparedStatement psmt = jdbc.prepareStatement("UPDATE pay.consolwages SET name1st = ?, rank1st = ?, name2nd = ?, rank2nd = ?, name3rd = ?, rank3rd = ? WHERE (consolid = ?);")) {

            psmt.setString(1, txt1stName.getText());
            psmt.setString(2, txt1stRank.getText());
            psmt.setString(3, txt2ndName.getText());
            psmt.setString(4, txt2ndRank.getText());
            psmt.setString(5, txt3rdName.getText());
            psmt.setString(6, txt3rdRank.getText());
            /*---------------------------------------------*/
            psmt.setString(7, BatchCtrl);
            psmt.executeUpdate();
    
            javax.swing.JOptionPane.showMessageDialog(this, "Signatory updated successfully.", title, javax.swing.JOptionPane.INFORMATION_MESSAGE);



        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(ConsolidateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_alterActionPerformed

    private void alobsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alobsItemActionPerformed
        // TODO add your handling code here:
        if (evt == null) return;
        
        java.io.InputStream reportSource = getClass().getResourceAsStream("/jreport/alobs.jasper");
        try (java.sql.Connection jdbc = new gov.hrisjo.PGdbLink("financial")) {
            
            String alobsid = fmtAlobsNo.getText();

            // REPORT PARAMETERS
            java.util.Map<String, Object> params = new java.util.HashMap<>();
            params.put("AlobsNo", alobsid);

            net.sf.jasperreports.engine.JasperPrint jasperPrint = net.sf.jasperreports.engine.JasperFillManager.fillReport(reportSource, params, jdbc);
            net.sf.jasperreports.view.JasperViewer.viewReport(jasperPrint, false);



        } catch (java.sql.SQLException | net.sf.jasperreports.engine.JRException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(ConsolidateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_alobsItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.lang.String BatchCtrl;
    private javax.swing.JMenuItem alobsItem;
    private javax.swing.JButton btnAlter;
    private javax.swing.JButton btnAppend;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> cboFunds;
    private javax.swing.JComboBox<String> cboSelect;
    private javax.swing.JMenuItem clearItems;
    private com.toedter.calendar.JDateChooser dtpDated;
    private javax.swing.JFormattedTextField fmtAlobsNo;
    private javax.swing.JFormattedTextField fmtTotal;
    private javax.swing.JPopupMenu menuPopup;
    private javax.swing.JMenuItem payrollItem;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JMenuItem removeItem;
    private javax.swing.JMenuItem retrieveItem;
    private javax.swing.JSpinner spnYear;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tblWages;
    private javax.swing.JTextField txt1stName;
    private javax.swing.JTextField txt1stRank;
    private javax.swing.JTextField txt2ndName;
    private javax.swing.JTextField txt2ndRank;
    private javax.swing.JTextField txt3rdName;
    private javax.swing.JTextField txt3rdRank;
    private javax.swing.JTextField txtBudgetary;
    private javax.swing.JTextField txtCtrlNo;
    private javax.swing.JTextField txtDeptHead;
    private javax.swing.JTextArea txtDetail;
    private javax.swing.JTextField txtOffice;
    private javax.swing.JTextField txtPayee;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtRanggo;
    // End of variables declaration//GEN-END:variables

    private final String TITLE = "Payroll Consolidation";
    private final String[] WAGES = {"timebook", "laborpaid"};
    private final String OFFICE_CODE = "1121-01"; // "1011-01";
    private final String OFFICE_NAME = "City Human Resource Management and Development Office";// "EXECUTIVE SERVICES (CMO)";
    
    private Boolean NotATM;
}
