package gov.find;

/**
 *
 * @author felix
 */
public class LocateFrame extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = -2589589417544082665L;

    /**
     * Creates new form LocateFrame
     */
    public LocateFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        tblLocate = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtLocate = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        spnYear = new javax.swing.JSpinner();

        setClosable(true);
        setTitle("Search/Locate Name");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tblLocate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ctrl No.", "Name", "Period", "Office", "Charges"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLocate.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblLocate.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblLocate);
        if (tblLocate.getColumnModel().getColumnCount() > 0) {
            tblLocate.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblLocate.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblLocate.getColumnModel().getColumn(2).setPreferredWidth(160);
            tblLocate.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblLocate.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        btnView.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnView.setText("Preview");
        btnView.setBorderPainted(false);
        btnView.setEnabled(false);
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Name:");

        btnSearch.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/search.png"))); // NOI18N
        btnSearch.setBorderPainted(false);
        btnSearch.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Year:");

        spnYear.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        spnYear.setModel(new javax.swing.SpinnerNumberModel(2000, 2000, 3000, 1));
        spnYear.setEditor(new javax.swing.JSpinner.NumberEditor(spnYear, "#0"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnView)
                        .addComponent(jLabel2)
                        .addComponent(spnYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSearch)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtLocate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(btnSearch);

        setBounds(0, 0, 909, 468);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        tblLocate.getSelectionModel().addListSelectionListener((javax.swing.event.ListSelectionEvent lse) -> {
            if (lse.getValueIsAdjusting()) return; //System.out.println("valueChanged");

            btnView.setEnabled(tblLocate.getSelectedRowCount() > 0);
        });
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.Statement _smt = jdbc.createStatement();
                java.sql.ResultSet rst = _smt.executeQuery("SELECT DATE_PART('YEAR', NOW());")) {
            if (rst.next()) spnYear.setValue(rst.getInt(1));

        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(LocateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String text = txtLocate.getText();
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.PreparedStatement psmt = jdbc.prepareStatement(
                        "SELECT " +
                            "humane(jobworker.lastname, jobworker.firstname, jobworker.suffix, jobworker.midname), " +
                            "jobarrange.frdate, " +
                            "jobarrange.todate, " +
                            "jobarrange.psnl_ref, " +
                            "offices.office, " +
                            "projects.projtitle " +
                        "FROM " +
                            "psnl.jobworker INNER JOIN cbo.jobarrange " +
                            "ON jobworker.uniqkey = jobarrange.empkey " +
                            "INNER JOIN cbo.projects " +
                            "ON jobarrange.project = projects.projid " +
                            "INNER JOIN psnl.offices " +
                            "ON jobarrange.offcloc = offices.offcid " +
                        "WHERE " +
                            "(jobarrange.jobyear = " + spnYear.getValue() + ") AND " +
                            "(UPPER(named(jobworker.lastname, jobworker.firstname, jobworker.midname)) LIKE '%" + text.toUpperCase() + "%') " +
                        "ORDER BY " +
                            "jobworker.lastname, jobworker.firstname, jobworker.midname, jobarrange.frdate");
                java.sql.ResultSet rst = psmt.executeQuery()) {
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblLocate.getModel();
            modelo.setRowCount(0);
            while (rst.next()) {
                Object[] rowData = {
                    rst.getString(4),
                    rst.getString(1),
                    new java.text.SimpleDateFormat("MM/dd/yyyy").format(rst.getDate(2)) +
                        "-" +
                    new java.text.SimpleDateFormat("MM/dd/yyyy").format(rst.getDate(3)),
                    rst.getString(5),
                    rst.getString(6)
                };
                modelo.addRow(rowData);
            }




        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(LocateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_searchActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        java.io.InputStream reportSource = getClass().getResourceAsStream("/jreport/newJobOrder.jasper");

        java.util.Map<String, Object> params = new java.util.HashMap<>();

//        org.apache.log4j.Logger logger = org.apache.log4j.Logger.getRootLogger();
//        logger.setLevel((org.apache.log4j.Level)org.apache.log4j.Level.WARN);

        try (java.sql.Connection jdbc = new gov.hrisjo.PGdbLink()) {
            
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)tblLocate.getModel();
            int index = tblLocate.getSelectedRow();
            index = tblLocate.convertRowIndexToModel(index);
            
            Short anios = Short.valueOf(spnYear.getValue().toString(), 10);
            
            // REPORT PARAMETERS
            params.put("ControlNo", modelo.getValueAt(index, 0).toString());
            params.put("Anios",     anios);

            net.sf.jasperreports.engine.JasperPrint jasperPrint = net.sf.jasperreports.engine.JasperFillManager.fillReport(reportSource, params, jdbc);
            net.sf.jasperreports.view.JasperViewer.viewReport(jasperPrint, false);



        } catch (java.sql.SQLException | net.sf.jasperreports.engine.JRException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(LocateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_viewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner spnYear;
    private javax.swing.JTable tblLocate;
    private javax.swing.JTextField txtLocate;
    // End of variables declaration//GEN-END:variables
}
