package gov.reports;

/**
 *
 * @author felix
 */
public class HistoryIFrame extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = -7709964880169438862L;

    /**
     * Creates new form HistoryIFrame
     */
    public HistoryIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListModelo = new javax.swing.DefaultListModel<>();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        lstList = new javax.swing.JList<>();
        btnPreview = new javax.swing.JButton();
        javax.swing.JButton btnClose = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        spnYear = new javax.swing.JSpinner();

        setClosable(true);
        setTitle("JOB ORDER HISTORY");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/history16.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        lstList.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lstList.setModel(ListModelo);
        jScrollPane1.setViewportView(lstList);

        btnPreview.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnPreview.setText("Preview");
        btnPreview.setEnabled(false);
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnClose.setText("Close");
        btnClose.setBorderPainted(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Select desired Year");

        spnYear.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        spnYear.setModel(new javax.swing.SpinnerNumberModel(2000, 2000, 3000, 1));
        spnYear.setEditor(new javax.swing.JSpinner.NumberEditor(spnYear, "#0"));
        spnYear.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnYearStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spnYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPreview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        lstList.addListSelectionListener((lste) -> {
            System.out.println(lste.getValueIsAdjusting());
            System.out.println(lste.getLastIndex());
            btnPreview.setEnabled(lstList.getSelectedIndex() >= 0);
        });

        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.PreparedStatement psmt = jdbc.prepareStatement("SELECT DATE_PART('YEAR', NOW());");
                java.sql.ResultSet rst = psmt.executeQuery()) {
            rst.next();
            spnYear.setValue(rst.getInt(1));
            


        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(HistoryIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewActionPerformed
        // TODO add your handling code here:
        java.io.InputStream reportSource = getClass().getResourceAsStream("/jreport/newJobOrder.jasper");

        java.util.Map<String, Object> params = new java.util.HashMap<>();

//        org.apache.log4j.Logger logger = org.apache.log4j.Logger.getRootLogger();
//        logger.setLevel((org.apache.log4j.Level)org.apache.log4j.Level.WARN);

        try (java.sql.Connection jdbc = new gov.hrisjo.PGdbLink()) {
            
            int index = lstList.getSelectedIndex();
            // REPORT PARAMETERS
            params.put("ControlNo", ListModelo.get(index));
            params.put("Anios",     Short.valueOf(spnYear.getValue().toString(), 10));

            net.sf.jasperreports.engine.JasperPrint jasperPrint = net.sf.jasperreports.engine.JasperFillManager.fillReport(reportSource, params, jdbc);
            net.sf.jasperreports.view.JasperViewer.viewReport(jasperPrint, false);



        } catch (java.sql.SQLException | net.sf.jasperreports.engine.JRException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(HistoryIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_previewActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        doDefaultCloseAction();
    }//GEN-LAST:event_closeActionPerformed

    private void spnYearStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnYearStateChanged
        // TODO add your handling code here:
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.PreparedStatement psmt = jdbc.prepareStatement("SELECT psnl_no FROM psnl.createdjob WHERE (LEFT(psnl_no, 4) = ?) ORDER BY sekwence;")) {
            
            psmt.setString(1, spnYear.getValue().toString());
            try (java.sql.ResultSet rst = psmt.executeQuery()) {
                ListModelo.clear();
                while (rst.next()) ListModelo.addElement(rst.getString(1));
            }


        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(HistoryIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {

        }
    }//GEN-LAST:event_spnYearStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.DefaultListModel<String> ListModelo;
    private javax.swing.JButton btnPreview;
    private javax.swing.JList<String> lstList;
    private javax.swing.JSpinner spnYear;
    // End of variables declaration//GEN-END:variables

}
