package gov.reports;

/**
 *
 * @author xiong
 */
public class JosCosWageJFrame extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;
    private final java.util.ArrayList<String> NameIds = new java.util.ArrayList<>();

    /**
     * Creates new form SummarizeJFrame
     */
    public JosCosWageJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JOsKey = new java.lang.String();
        javax.swing.JButton cmdView = new javax.swing.JButton();
        javax.swing.JButton cmdPrint = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        cboBoxFr = new javax.swing.JComboBox<>();
        cboBoxTo = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        spnYear = new javax.swing.JSpinner();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        spnAnios = new javax.swing.JSpinner();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        cboBulan = new javax.swing.JComboBox<>();
        cboName = new organize.JComboDynamicWidth<>();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("JOs & COS Nakasweldo");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        cmdView.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cmdView.setText("Preview");
        cmdView.setBorderPainted(false);
        cmdView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        cmdPrint.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cmdPrint.setText("Print");
        cmdPrint.setBorderPainted(false);
        cmdPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Year");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("From");

        cboBoxFr.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        cboBoxTo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("To");

        spnYear.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        spnYear.setModel(new javax.swing.SpinnerNumberModel(2000, 2000, 3000, 1));
        spnYear.setEditor(new javax.swing.JSpinner.NumberEditor(spnYear, "#0"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboBoxTo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboBoxFr, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cboBoxTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboBoxFr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Period Covered", jPanel1);

        spnAnios.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        spnAnios.setModel(new javax.swing.SpinnerNumberModel(2000, 2000, 3000, 1));
        spnAnios.setEditor(new javax.swing.JSpinner.NumberEditor(spnAnios, "#0"));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Year");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Month");

        cboBulan.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cboBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        cboName.setEditable(true);
        cboName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cboName.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                namePopupMenuWillBecomeVisible(evt);
            }
        });
        cboName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 127, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        tabbedPane.addTab("JO's/COS Monitoring", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdPrint))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdView)
                    .addComponent(cmdPrint))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        int year = Integer.parseInt(System.getProperty("ANIOS"), 10);
        
        java.util.Calendar cal = java.util.Calendar.getInstance();
        for (int xyz = 0; xyz < 12; xyz++) {
            cal.set(year, xyz, 1);
            String month = new java.text.SimpleDateFormat("MMMM").format(cal.getTime());
            cboBoxFr.addItem(month + " - 01");
            cboBoxTo.addItem(month + " - 15");
        }
        for (int xyz = 0; xyz < 12; xyz++) {
            cal.set(year, xyz, 1);
            String month = new java.text.SimpleDateFormat("MMMM").format(cal.getTime());
            cal.set(year, xyz + 1, 0);
            cboBoxFr.addItem(month + " - 16");
            cboBoxTo.addItem(month + " - " + cal.get(java.util.Calendar.DATE));
        }
        spnYear.setValue(year);
        spnAnios.setValue(year);
        
        java.util.Calendar calz = java.util.Calendar.getInstance();
        calz.set(java.util.Calendar.YEAR, year);
        cboBulan.setSelectedIndex(calz.get(java.util.Calendar.MONTH));
    }//GEN-LAST:event_formInternalFrameOpened

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        new Thread(() -> {
            try (java.sql.Connection jdbc = new gov.hrisjo.PGdbLink()) {
                java.io.InputStream reportSource;
                java.util.Map<String, Object> params = new java.util.HashMap<>(); // REPORT PARAMETERS
                
                
                switch (tabbedPane.getSelectedIndex()) {
                    case 0 -> {
                        String value = cboBoxFr.getSelectedItem().toString(),
                               balor = cboBoxTo.getSelectedItem().toString();
                        int index = cboBoxFr.getSelectedIndex(),
                            length, lapads,
                            endix = cboBoxTo.getSelectedIndex(),
                            anios = (Integer)spnYear.getValue();

                        length = value.length();
                        lapads = balor.length();
                        value = value.substring(length - 2);
                        balor = balor.substring(lapads - 2);
                        int from = Integer.parseInt(value),
                            toos = Integer.parseInt(balor);

                        java.util.Calendar calfr = java.util.Calendar.getInstance(),
                                           calto = java.util.Calendar.getInstance();

                        calfr.set(anios, (index % 12), from, 0, 0, 0);
                        calto.set(anios, (endix % 12), toos, 0, 0, 0);

                        params.put("DateFr", calfr.getTime());
                        params.put("DateTo", calto.getTime());
                        reportSource = getClass().getResourceAsStream("/jreport/dumlao.jasper");
                    }
                    default -> {
                        int anios = (Integer)spnAnios.getValue();
                        
                        String[] actgRefz = JOsKey.split("~");
                        
                        params.put("Anios",  (short)anios);
                        params.put("ActgRefz", actgRefz);
                        reportSource = getClass().getResourceAsStream("/jreport/nakasweldo.jasper");
                    }
                }
                boolean check = evt.getActionCommand().equals("Print");
                net.sf.jasperreports.engine.JasperPrint jasperPrint = net.sf.jasperreports.engine.JasperFillManager.fillReport(reportSource, params, jdbc);
                if (check)
                    net.sf.jasperreports.engine.JasperPrintManager.printReport(jasperPrint, true);
                else
                    net.sf.jasperreports.view.JasperViewer.viewReport(jasperPrint, false);



            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
                java.util.logging.Logger.getLogger(JosCosWageJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } finally {

            }
        }).start();
    }//GEN-LAST:event_viewActionPerformed

    private void namePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_namePopupMenuWillBecomeVisible
        // TODO add your handling code here:
        if (evt == null) return;

        String xxxx = cboName.getEditor().getItem().toString();
        if (!xxxx.isBlank()) loadNames(xxxx);
    }//GEN-LAST:event_namePopupMenuWillBecomeVisible

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
        if (evt == null) return;
        
        short much = (short)cboName.getSelectedIndex();
        if (much < 0) return;
        
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink()) {
            
            Short bulan = (short)(cboBulan.getSelectedIndex() + 1),
                  anios = Short.valueOf(spnAnios.getValue().toString(), 10),
                  checkit;
            String wrkid = NameIds.get(much), refkey = "";
            
            //Check if there is an advice.
            try (java.sql.PreparedStatement psmt = jdbc.prepareStatement(
                    "SELECT advicekey, acctg_ref FROM pay.timebook WHERE (worker = ?) AND paid_up AND (DATE_PART('MONTH', datefr) = ?) AND (DATE_PART('YEAR', datefr) = ?) " +
                    "UNION ALL " +
                    "SELECT advicekey, acctg_ref FROM pay.laborpaid WHERE (worker = ?) AND paid_up AND (DATE_PART('MONTH', datefr) = ?) AND (DATE_PART('YEAR', datefr) = ?);")) {
                psmt.setString(1, wrkid);
                psmt.setShort (2, bulan);
                psmt.setShort (3, anios);
               /**----------------------*/
                psmt.setString(4, wrkid);
                psmt.setShort (5, bulan);
                psmt.setShort (6, anios);
                try (java.sql.ResultSet rst = psmt.executeQuery()) {
                   if (rst.next()) {
                       boolean test = rst.getString(1) == null;
                       checkit = test ? (short)-1 : (short)1;
                       refkey  = test ? rst.getString(2) : rst.getString(1);
                   } else
                       checkit = 0;
                }
            }
            switch (checkit) {
                case -1 -> //meaning cash advance
                    JOsKey = findAdvances(refkey);
                
                case 0 -> //meaning no payroll
                    javax.swing.JOptionPane.showMessageDialog(this, "No Payroll yet!", title, javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
                default -> //meaning ATM
                    JOsKey = findAdvice(refkey);
            }
            System.out.println(JOsKey);
        
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(JosCosWageJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {
            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_nameActionPerformed
    private void loadNames(String names) {
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.PreparedStatement psmt = jdbc.prepareStatement(
                        "SELECT " +
                            "uniqkey, " +
                            "humane(lastname, firstname, suffix, midname) as ngalan " +
                        "FROM " +
                            "psnl.jobworker " +
                        "WHERE " +
                            "(UPPER(CONCAT(lastname, COALESCE(firstname, ''), COALESCE(midname, ''))) LIKE ?) " +
                        "ORDER BY " +
                            "lastname, firstname;")) {
            boolean checking = true;
            psmt.setString(1, "%" + names.toUpperCase() + "%");
            try (java.sql.ResultSet rst = psmt.executeQuery()) {
                while (rst.next()) {
                    if (checking) {
                        NameIds.clear(); cboName.removeAllItems();
                        checking = false;
                    }
                    NameIds.add(rst.getString(1));
                    cboName.addItem(rst.getString(2));
                }
            }
                
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(JosCosWageJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {
            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }
    }
    private String findAdvances(String acctgref) {
        String voucher = "";
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink("treasurer")) {
            //StringBuilder acctref = new StringBuilder();
            try (java.sql.PreparedStatement psmt = jdbc.prepareStatement("SELECT voucher FROM adv.payrolls WHERE (acctgref = ?);")) {
                psmt.setString(1, acctgref);
                try (java.sql.ResultSet rst = psmt.executeQuery()) {
                    if (rst.next()) 
                        voucher = rst.getString(1);
                    else
                        voucher = "";
                }
            }
            if (voucher.isEmpty()) javax.swing.JOptionPane.showMessageDialog(this, "No Cash Advance yet.", title, javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            try (java.sql.PreparedStatement psmt = jdbc.prepareStatement("SELECT acctgref FROM adv.payrolls WHERE (voucher = ?);")) {
                psmt.setString(1, voucher);
                try (java.sql.ResultSet rst = psmt.executeQuery()) {
                    StringBuilder acctref = new StringBuilder();
                    while (rst.next()) 
                        acctref.append(rst.getString(1)).append("~");
                    int test = acctref.length();
                    if (test > 0) {
                        acctref.deleteCharAt(test - 1);
                        voucher = acctref.toString();
                    }
                }
            }
            
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(JosCosWageJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        return voucher;
    }
    private String findAdvice(String debitkey) {
        String voucher = "";
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink()) {
            try (java.sql.PreparedStatement psmt = jdbc.prepareStatement("SELECT DISTINCT acctg_ref FROM pay.timebook WHERE (advicekey = ?) " +
                                                                         "UNION ALL " +
                                                                         "SELECT DISTINCT acctg_ref FROM pay.laborpaid WHERE (advicekey = ?);")) {
                psmt.setString(1, debitkey);
                psmt.setString(2, debitkey);
                try (java.sql.ResultSet rst = psmt.executeQuery()) {
                    StringBuilder acctref = new StringBuilder();
                    while (rst.next()) 
                        acctref.append(rst.getString(1)).append("~");
                    int test = acctref.length();
                    if (test > 0) {
                        acctref.deleteCharAt(test - 1);
                        voucher = acctref.toString();
                    }
                }
            }
            
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(JosCosWageJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        return voucher;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.lang.String JOsKey;
    private javax.swing.JComboBox<String> cboBoxFr;
    private javax.swing.JComboBox<String> cboBoxTo;
    private javax.swing.JComboBox<String> cboBulan;
    private javax.swing.JComboBox<String> cboName;
    private javax.swing.JSpinner spnAnios;
    private javax.swing.JSpinner spnYear;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

}
