/*
 * ConsolidateRpt.java
 *
 * Created on March 10, 2008, 9:27 AM
 */

package gov.reports;

/**
 *
 * @author  felixiong
 */
public class UnservedRpt extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;
    
    private final java.util.ArrayList<String> arOpesina = new java.util.ArrayList<>();
    private final java.util.List<java.util.Date> aUntil = new java.util.ArrayList<>();
    
//    private String appPath = System.getProperties().getProperty("user.dir");
    
    /** Creates new form ConsolidateRpt */
    public UnservedRpt() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JButton btnPrint = new javax.swing.JButton();
        javax.swing.JButton btnClose = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        cboOffice = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        cboDays = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        javax.swing.JButton btnPrint1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("UNSERVED J.O. LISTING");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/leaf.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("OFFICE");

        btnPrint.setForeground(java.awt.Color.red);
        btnPrint.setText("View Summary");
        btnPrint.setBorderPainted(false);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryPerformPrint(evt);
            }
        });

        btnClose.setForeground(java.awt.Color.red);
        btnClose.setText("CLOSE");
        btnClose.setBorderPainted(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerformClose(evt);
            }
        });

        lblStatus.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText(".");

        cboOffice.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cboOffice.setMaximumRowCount(19);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("J.O. with Ending date of");

        cboDays.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("C.Y.");

        txtYear.setEditable(false);

        btnPrint1.setForeground(java.awt.Color.red);
        btnPrint1.setText("View Detail");
        btnPrint1.setBorderPainted(false);
        btnPrint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailPerformPrint(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrint)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrint1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose))
                    .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint)
                    .addComponent(btnClose)
                    .addComponent(btnPrint1))
                .addGap(18, 18, 18)
                .addComponent(lblStatus)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void summaryPerformPrint(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryPerformPrint
        // TODO add your handling code here:
        lblStatus.setText("Previewing report, please wait....");
        java.io.InputStream reportSource = getClass().getResourceAsStream("/jreport/unservedsum.jasper");
        java.io.InputStream subrptSource = getClass().getResourceAsStream("/subrpt/subunserved.jrxml");
        

        java.util.Map<String, Object> params = new java.util.HashMap<>();

        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink()) {
            net.sf.jasperreports.engine.JasperReport jasperSubReport = net.sf.jasperreports.engine.JasperCompileManager.compileReport(subrptSource);
            
            int petsa = cboDays.getSelectedIndex();
            java.util.Date datedon = aUntil.get(petsa);
            int index = cboOffice.getSelectedIndex();
            String office = arOpesina.get(index);

            // REPORT PARAMETERS
            params.put("Opesina", office);
            params.put("DatedOn", datedon);
            params.put("mySubReport", jasperSubReport);

            net.sf.jasperreports.engine.JasperPrint jasperPrint = net.sf.jasperreports.engine.JasperFillManager.fillReport(reportSource, params, jdbc);
            net.sf.jasperreports.view.JasperViewer.viewReport(jasperPrint, false);
            lblStatus.setText("");

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(UnservedRpt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_summaryPerformPrint

    private void PerformClose(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerformClose
        // TODO add your handling code here:
        this.doDefaultCloseAction();
    }//GEN-LAST:event_PerformClose

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        lblStatus.setText("");
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.PreparedStatement psmt = jdbc.prepareStatement(
                    "SELECT DISTINCT " +
                        "jobarrange.offcloc, " +
                        "offices.office " +
                    "FROM " +
                        "cbo.jobarrange INNER JOIN psnl.offices " +
                        "ON jobarrange.offcloc = offices.offcid " +
                    "WHERE " +
                        "(jobarrange.jobyear = ?) " +
                    "ORDER BY " +
                        "offices.office");
                java.sql.PreparedStatement pzmt = jdbc.prepareStatement("SELECT DATE_PART('YEAR', MAX(datefr)) FROM pay.timebook;")) {
            java.util.Calendar cald = java.util.Calendar.getInstance();
            
            try (java.sql.ResultSet rst = pzmt.executeQuery()) {
                if (rst.next()) Anios = rst.getShort(1);
            }
            
            psmt.setShort(1, Anios);
            try (java.sql.ResultSet rst = psmt.executeQuery()) {
                cboOffice.removeAllItems(); arOpesina.clear();
//                cboOffice.addItem("<ALL OFFICES>");
//                arOpesina.add("");
                while (rst.next()) {
                    arOpesina.add(rst.getString(1));
                    cboOffice.addItem(rst.getString(2));
                }
            }
            txtYear.setText(Anios.toString());
//            cald.set(Anios, 0, 1);
//            calDateFr.setMinSelectableDate(cald.getTime());
//            calDateTo.setMinSelectableDate(cald.getTime());
//            
//            cald.set(Anios, 11, 31);
//            calDateFr.setMaxSelectableDate(cald.getTime());
//            calDateTo.setMaxSelectableDate(cald.getTime());
            

        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(UnservedRpt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {
            
        }
        
        java.util.Calendar cal = java.util.Calendar.getInstance();
        for (short xyz = 0; xyz < 12; xyz++) {
            cal.set(Anios, xyz, 1);
            String month = new java.text.SimpleDateFormat("MMMM").format(cal.getTime());
            
            cal.set(Anios, xyz, 15);
            cboDays.addItem(month + " - 15");
            aUntil.add(cal.getTime());

            cal.set(Anios, xyz + 1, 0);
            cboDays.addItem(month + " - " + cal.get(java.util.Calendar.DATE));
            aUntil.add(cal.getTime());            
        }   
    }//GEN-LAST:event_formInternalFrameOpened

    private void detailPerformPrint(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailPerformPrint
        // TODO add your handling code here:
        lblStatus.setText("Previewing report, please wait....");
        java.io.InputStream reportSource = getClass().getResourceAsStream("/jreport/unservedlist.jasper");
        

        java.util.Map<String, Object> params = new java.util.HashMap<>();

        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink()) {
            int petsa = cboDays.getSelectedIndex();
            java.util.Date datedon = aUntil.get(petsa);
            int index = cboOffice.getSelectedIndex();
            String office = arOpesina.get(index);

            // REPORT PARAMETERS
            params.put("Opesina", office);
            params.put("DatedOn", datedon);

            net.sf.jasperreports.engine.JasperPrint jasperPrint = net.sf.jasperreports.engine.JasperFillManager.fillReport(reportSource, params, jdbc);
            net.sf.jasperreports.view.JasperViewer.viewReport(jasperPrint, false);
            lblStatus.setText("");

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(UnservedRpt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_detailPerformPrint


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboDays;
    private javax.swing.JComboBox<String> cboOffice;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables

    private Short Anios;
    //private String[] Buwana = { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" };
}
