/*
 * ConsolidateRpt.java
 *
 * Created on March 10, 2008, 9:27 AM
 */

package gov.reports;

/**
 *
 * @author  felixiong
 */
public class UnservedRpt extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;
    
    
//    private String appPath = System.getProperties().getProperty("user.dir");
    
    /** Creates new form ConsolidateRpt */
    public UnservedRpt() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JButton btnPrint = new javax.swing.JButton();
        javax.swing.JButton btnClose = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        spnYear = new javax.swing.JSpinner();
        cboMonth = new javax.swing.JComboBox<>();
        chkDetail = new javax.swing.JCheckBox();
        cboChoice = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("UNSERVED J.O. LISTING");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/imajen/leaf.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        btnPrint.setForeground(java.awt.Color.red);
        btnPrint.setText("Preview");
        btnPrint.setBorderPainted(false);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryPerformPrint(evt);
            }
        });

        btnClose.setForeground(java.awt.Color.red);
        btnClose.setText("CLOSE");
        btnClose.setBorderPainted(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerformClose(evt);
            }
        });

        lblStatus.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText(".");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Date");

        spnYear.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)2000), Short.valueOf((short)2000), Short.valueOf((short)3000), Short.valueOf((short)1)));
        spnYear.setEditor(new javax.swing.JSpinner.NumberEditor(spnYear, "#0"));

        cboMonth.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        chkDetail.setText("Detailed?");
        chkDetail.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        cboChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Job Orders", "Contract of Service" }));

        new dbase.dcare.AutoCompleteCombo<String>();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrint)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClose))
                            .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chkDetail)
                            .addComponent(cboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint)
                    .addComponent(btnClose)
                    .addComponent(cboChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblStatus)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void summaryPerformPrint(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryPerformPrint
        // TODO add your handling code here:
        lblStatus.setText("Previewing report, please wait....");
        int which = cboChoice.getSelectedIndex();
        String[] rptFile = {"unservedsum", "unservedcos"};
        java.io.InputStream reportSource = getClass().getResourceAsStream("/jreport/" + rptFile[which] + ".jasper");
        

        java.util.Map<String, Object> params = new java.util.HashMap<>();

        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink()) {
            
            
            java.util.Calendar calfr = java.util.Calendar.getInstance(),
                               calto = java.util.Calendar.getInstance();
            int bulan = cboMonth.getSelectedIndex(),
                tuiga = Integer.parseInt(spnYear.getValue().toString(), 10),
                lastd;
            lastd = java.time.YearMonth.of(tuiga, (bulan + 1)).atEndOfMonth().getDayOfMonth();
            
            calto.set(tuiga, bulan, lastd);
            calfr.set(tuiga, bulan, 1);

            // REPORT PARAMETERS
            params.put("DatedFr", calfr.getTime());
            params.put("DatedTo", calto.getTime());
            params.put("IsDetail", chkDetail.isSelected());

            net.sf.jasperreports.engine.JasperPrint jasperPrint = net.sf.jasperreports.engine.JasperFillManager.fillReport(reportSource, params, jdbc);
            net.sf.jasperreports.view.JasperViewer.viewReport(jasperPrint, false);
            lblStatus.setText("");

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(UnservedRpt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_summaryPerformPrint

    private void PerformClose(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerformClose
        // TODO add your handling code here:
        this.doDefaultCloseAction();
    }//GEN-LAST:event_PerformClose

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        lblStatus.setText("");
        try (org.postgresql.core.BaseConnection jdbc = new gov.hrisjo.PGdbLink();
                java.sql.PreparedStatement pzmt = jdbc.prepareStatement("SELECT DATE_PART('YEAR', MAX(datefr)) FROM pay.timebook;")) {
            java.util.Calendar cald = java.util.Calendar.getInstance();
            
            try (java.sql.ResultSet rst = pzmt.executeQuery()) {
                if (rst.next()) Anios = rst.getShort(1);
            }
            spnYear.setValue(Anios);
            cboMonth.setSelectedIndex(cald.get(java.util.Calendar.MONTH));
            

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), title, javax.swing.JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(UnservedRpt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {
            
        }
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboChoice;
    private javax.swing.JComboBox<String> cboMonth;
    private javax.swing.JCheckBox chkDetail;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JSpinner spnYear;
    // End of variables declaration//GEN-END:variables

    private Short Anios;
    //private String[] Buwana = { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" };
}
